src/MoreActionsPopover.tsx, src/Toolbar.tsx
=> Adjust tooltip position for left and right buttons in toolbar

CHANGELOG.md, LICENSE.md, README.md, demo/latest/src/App.tsx, demo/latest/src/SinglePageViewExample.tsx, dist/index.d.ts, src/Viewer.tsx, src/layouts/Inner.tsx
for #88 
~~~ javascript
<Viewer
fileUrl='/path/to/document.pdf'
defaultScale={SpecialZoomLevel.PageFit}
/>
~~~
=> The default scale can be a special zoom level

CHANGELOG.md, demo/latest/src/App.tsx, demo/latest/src/RenderErrorExample.tsx, dist/index.d.ts, src/Viewer.tsx, src/index.ts, src/loader/DocumentLoader.tsx, src/loader/FailureState.ts, src/loader/LoadError.ts
fix #65 
~~~ javascript
const renderError = (error: LoadError) => {
let message = '';
switch (error.name) {
case 'InvalidPDFException':
message = 'The document is invalid or corrupted';
break;
case 'MissingPDFException':
message = 'The document is missing';
break;
case 'UnexpectedResponseException':
message = 'Unexpected server response';
break;
default:
message = 'Cannot load the document';
break;
}
return (<div>{message}</div>);
};
<Viewer
fileUrl={fileUrl}
renderError={renderError}
/>
~~~
=> feat: Customize error renderer

CHANGELOG.md, src/layouts/Inner.tsx, src/open/dropArea.less
=> fix: The drag zone isn't visible if the main area is scrolled

CHANGELOG.md, src/layouts/Inner.tsx
=> fix: The viewer doesn't jump to the destination or searching result exactly

CHANGELOG.md, demo/character-map/CharacterMapExample.tsx, dist/index.d.ts, src/Viewer.tsx, src/Worker.tsx, src/annotations/useTogglePopup.ts, src/hooks/useKeyUp.ts, src/hooks/useLockScroll.ts, src/hooks/useToggle.ts, src/loader/DocumentLoader.tsx, src/print/PrintZone.tsx, src/vendors/PdfJs.d.ts
for #107 
Sample file: https://tcpdf.org/files/examples/example_033.pdf
The viewer downloads the following cmaps:
=> feat: Support non-latin characters

src/layouts/Inner.tsx, src/loader/DocumentLoader.tsx, src/vendors/PdfJs.d.ts
Related to #107 
The open document params are changed if we add `cmap`.
=> Fix an issue that can't open file from bytes

CHANGELOG.md, packages/core/src/Viewer.tsx, packages/core/src/index.d.ts, packages/core/src/loader/DocumentLoader.tsx, packages/core/src/vendors/PdfJs.d.ts
for #203
~~~ javascript
import { Viewer } from '@react-pdf-viewer/core';
<Viewer
fileUrl={...}
authorization='test'
httpHeaders={{
key1: 'value1',
key2: 'value2',
}}
/>
~~~
=> feat(core): Support loading PDF from a protected resource

CHANGELOG.md, demo/src/App.tsx, packages/core/src/layouts/Inner.tsx
=> feat(core): Keep the current page and scroll position after zooming the document

CHANGELOG.md, packages/default-layout/src/styles/defaultLayout.less
=> fix(default-layout): Can't scroll between pages on Safari 14

CHANGELOG.md, packages/core/src/layouts/Inner.tsx
=> fix: Clicking a bookmark doesn't jump to the destination properly

CHANGELOG.md, packages/core/src/annotations/Link.tsx
=> fix(core): Clicking on an internal link jumps to an incorrect page

packages/core/src/styles/index.less, packages/core/src/styles/utils.less, packages/toolbar/src/MoreActionsPopover.tsx, packages/toolbar/src/defaultToolbar.tsx
for #385 
_Mobile phone_
_Tablet_
=> feat(toolbar): Adjust the default toolbar in different screen sizes

CHANGELOG.md, packages/thumbnail/src/styles/thumbnailContainer.less, packages/thumbnail/src/styles/thumbnailList.less
=> fix(thumbnails): There are big spaces between thumbnails

CHANGELOG.md, demo/src/App.tsx, packages/core/src/Viewer.tsx, packages/core/src/layouts/Inner.tsx, packages/core/src/layouts/PageSizeCalculator.tsx
for #164 
for #489 
_Demo_
```js
<Viewer
fileUrl='...'
initialPage={3}
defaultScale={0.5}
/>
```
```js
<Viewer
fileUrl='...'
initialPage={3}
defaultScale={1.0}
/>
```
```js
<Viewer
fileUrl='...'
initialPage={3}
defaultScale={2.0}
/>
```
```js
<Viewer
fileUrl='...'
initialPage={3}
defaultScale={SpecialZoomLevel.PageFit}
/>
```
=> fix(core): The initialPage and defaultScale options don't work together

CHANGELOG.md, packages/core/src/portal/ModalBody.tsx, packages/core/src/portal/PopoverOverlay.tsx
=> fix(core): Fix warning when pressing Esc key to close a modal

CHANGELOG.md, packages/search/src/Tracker.tsx
=> fix: The search highlight elements should be shown below the text

CHANGELOG.md, packages/core/src/styles/textLayer.scss
=> fix: Don't highlight the entire page when selecting multiple lines

CHANGELOG.md, packages/search/src/Highlights.tsx
=> fix: Can't search or set the initial keyword for scanned documents

CHANGELOG.md, packages/core/src/annotations/Link.tsx
=> fix: Link annotations with unsafe URLs won't be rendered
