package.json
=> Copy CSS files when compiling to es6

demo/parcel/.gitignore, demo/parcel/README.md, demo/parcel/package-lock.json, demo/parcel/package.json, demo/parcel/src/App.jsx, demo/parcel/src/index.html, demo/parcel/src/index.jsx, demo/parcel/vendors/.gitignore, demo/webpack/.gitignore, demo/webpack/vendors/.gitignore
Bundle with [Parcel](https://parceljs.org)
=> Add a Parcel demo

demo/webpack-typescript/.babelrc, demo/webpack-typescript/.gitignore, demo/webpack-typescript/README.md, demo/webpack-typescript/package-lock.json, demo/webpack-typescript/package.json, demo/webpack-typescript/src/App.tsx, demo/webpack-typescript/src/index.html, demo/webpack-typescript/src/index.tsx, demo/webpack-typescript/tsconfig.json, demo/webpack-typescript/vendors/.gitignore, demo/webpack-typescript/webpack.config.js
=> Add a Typescript demo bundled with Webpack

src/Toolbar.tsx
=> Fix unnecessary ToolbarSlot import

demo/customize-layout/.babelrc, demo/customize-layout/.gitignore, demo/customize-layout/README.md, demo/customize-layout/package-lock.json, demo/customize-layout/package.json, demo/customize-layout/src/AlwaysShowSidebar.jsx, demo/customize-layout/src/App.jsx, demo/customize-layout/src/SimpleToolbar.jsx, demo/customize-layout/src/index.html, demo/customize-layout/src/index.jsx, demo/customize-layout/vendors/.gitignore, demo/customize-layout/webpack.config.js
Fix #11 
This consists of two examples:
_Simple toolbar_
_Always showing the sidebar_
=> Add layout customization demo

package.json, src/Observer.tsx, src/PageSizeCalculator.tsx, src/hooks/useToggle.ts, src/index.ts, src/layouts/ToolbarSlot.ts, src/loader/LoadingStatus.ts, src/localization/LocalizationContext.ts, src/portal/Portal.tsx, tsconfig.json
=> Cannot re-export a type when --isolatedModules is set to true

README.md, demo/webpack-typescript/webpack.config.js, src/PageSizeCalculator.tsx, src/ViewerInner.tsx
=> The document should fit best in the container initially

dist/index.d.ts, src/MoreActionsPopover.tsx, src/SelectionMode.ts, src/Toolbar.tsx, src/Viewer.tsx, src/ViewerInner.tsx, src/index.ts, src/print/PageThumbnail.tsx, src/print/PageThumbnailContainer.tsx
=> Selection mode

dist/index.d.ts, src/Viewer.tsx, src/ViewerInner.tsx
=> Add callback for document loaded

dist/index.d.ts, src/Viewer.tsx, src/ViewerInner.tsx
=> Add callback option for zooming

src/PageSizeCalculator.tsx, src/Spinner.tsx, src/loader/DocumentLoader.tsx
=> The view now takes the full height by default

CHANGELOG.md, dist/package.json, package-lock.json, package.json, postcss.config.js
=> Bump v1.2.1

demo/latest/src/CustomToolbar.tsx, demo/latest/src/index.html, src/layouts/defaultLayout.css, src/layouts/defaultLayout.tsx
for #50 
* IE 11 doesn't support array's `find`, `findIndex` methods
* IE 11 doesn't support IntersectionObserver
* IE 11 doesn't support grid-template-areas
=> Add polyfills and fix the layout in IE 11

src/print/PageThumbnail.tsx
=> The printing doesn't work in IE 11

CHANGELOG.md, dist/index.d.ts, src/layouts/defaultLayout.less, src/layouts/sidebar.less
=> Small tweak for the default layout

CHANGELOG.md, demo/latest/src/App.tsx, demo/latest/src/JumpToPage.tsx, demo/latest/src/RenderPropsExample.tsx, dist/index.d.ts, src/File.ts, src/SpecialZoomLevel.ts, src/Viewer.tsx, src/bookmark/BookmarkItem.tsx, src/bookmark/BookmarkList.tsx, src/bookmark/BookmarkLoader.tsx, src/index.ts, src/layers/AnnotationLayer.tsx, src/layers/PageLayer.tsx, src/layouts/Inner.tsx, src/layouts/Sidebar.tsx, src/layouts/Toolbar.tsx, src/layouts/inner.less, src/utils/getDestination.ts, src/zoom/ZoomPopover.tsx, src/zoom/zoomingLevel.ts, tsconfig.json
=> Add new render parameter

CHANGELOG.md, README.md, demo/latest/src/App.tsx, demo/latest/src/InitialPageExample.tsx, dist/index.d.ts, src/Viewer.tsx, src/layers/PageLayer.tsx, src/layouts/Inner.tsx
=> Add initial page option

CHANGELOG.md, src/print/PrintZone.tsx
=> Printing doesn't look good if the page size isn't set

CHANGELOG.md, rollup.config.js, rollup.dev.config.js, src/print/PageThumbnail.tsx, src/print/PrintZone.tsx, src/print/printZone.less
=> Blank page when print the current web page

CHANGELOG.md, demo/latest/src/App.tsx, demo/latest/src/KeywordExample.tsx, dist/index.d.ts, src/Viewer.tsx, src/layouts/Inner.tsx
=> Highlight given keyword in the first render

CHANGELOG.md, demo/latest/src/App.tsx, demo/latest/src/WaterMarkExample.tsx, dist/index.d.ts, src/Viewer.tsx, src/layers/PageLayer.tsx, src/layouts/Inner.tsx, src/layouts/RenderPage.tsx
=> Page renderer

demo/latest/src/PreviewLocalFile.tsx
=> Add preview local file example

CHANGELOG.md, demo/latest/src/App.tsx, demo/latest/src/SvgLayerExample.tsx, dist/index.d.ts, src/layers/PageLayer.tsx, src/layers/SvgLayer.tsx, src/layouts/RenderPage.tsx, src/vendors/PdfJs.d.ts
=> feat: Add SVG layer

CHANGELOG.md, src/annotations/Annotation.tsx, src/annotations/AnnotationLayer.tsx, src/annotations/AnnotationLoader.tsx, src/annotations/AnnotationType.ts, src/annotations/Link.tsx, src/annotations/annotation.less, src/annotations/link.less, src/layers/PageLayer.tsx, src/vendors/PdfJs.d.ts
=> Link annotation

CHANGELOG.md, demo/latest/src/App.tsx, demo/latest/src/CanvasLayerExample.tsx, src/layers/CanvasLayer.tsx, src/layers/WithScale.tsx, src/layers/canvasLayer.less
=> fix: Fix canvas blurry

CHANGELOG.md, demo/latest/src/App.tsx, src/components/menuItem.less, src/hooks/useClickOutside.ts, src/hooks/useKeyUp.ts, src/hooks/usePosition.ts, src/layouts/defaultLayout.less, src/portal/Modal.tsx, src/portal/ModalBody.tsx, src/portal/ModalOverlay.tsx, src/portal/Popover.tsx, src/portal/PopoverBody.tsx, src/portal/PopoverOverlay.tsx, src/portal/Portal.tsx, src/portal/TooltipBody.tsx, src/portal/popoverOverlay.less, src/portal/tooltipBody.less, src/utils/calculatePosition.ts, src/zoom/zoomPopover.less
=> fix: Fix portal position

README.md, demo/latest/src/App.tsx, src/Viewer.tsx, src/hooks/useToggle.ts, src/index.ts, src/layouts/Layout.ts, src/layouts/RenderPage.tsx, src/layouts/ToolbarSlot.ts, src/loader/DocumentLoader.tsx, src/loader/LoadingStatus.ts, src/localization/LocalizationContext.ts, src/portal/Portal.tsx
=> Cleanup exported types

demo/latest/src/App.tsx, src/annotations/Annotation.tsx, src/annotations/AnnotationLayer.tsx, src/annotations/AnnotationType.ts, src/annotations/Link.tsx, src/annotations/Popup.tsx, src/annotations/PopupWrapper.tsx, src/annotations/Text.tsx, src/annotations/popupWrapper.less, src/annotations/useTogglePopup.ts, src/vendors/PdfJs.d.ts
=> feat: Text and Popup annotations

CHANGELOG.md, src/annotations/Annotation.tsx, src/annotations/AnnotationBorderStyleType.ts, src/vendors/PdfJs.d.ts
=> feat(annotation): Support annotation border

CHANGELOG.md, src/annotations/AnnotationLayer.tsx, src/annotations/AnnotationType.ts, src/annotations/FreeText.tsx
=> feat(annotation): Support free text annotation

CHANGELOG.md, src/annotations/Annotation.tsx, src/annotations/AnnotationLayer.tsx, src/annotations/AnnotationType.ts, src/annotations/Link.tsx, src/annotations/Popup.tsx, src/annotations/Square.tsx, src/annotations/Text.tsx, src/vendors/PdfJs.d.ts
=> feat(annotation): Add square annotation

CHANGELOG.md, src/annotations/Annotation.tsx, src/annotations/AnnotationLayer.tsx, src/annotations/AnnotationType.ts, src/annotations/Line.tsx, src/vendors/PdfJs.d.ts
=> feat(annotation): Add line annotation

CHANGELOG.md, src/annotations/AnnotationLayer.tsx, src/annotations/AnnotationType.ts, src/annotations/Stamp.tsx
=> feat(annotation): Add stamp annotation

CHANGELOG.md, src/annotations/AnnotationLayer.tsx, src/annotations/AnnotationType.ts, src/annotations/Circle.tsx, src/annotations/Line.tsx
=> feat(annotation): Add circle annotation

CHANGELOG.md, src/annotations/AnnotationLayer.tsx, src/annotations/AnnotationType.ts, src/annotations/Underline.tsx
=> feat(annotation): Add underline annotation

CHANGELOG.md, src/annotations/AnnotationLayer.tsx, src/annotations/AnnotationType.ts, src/annotations/Highlight.tsx
=> feat(annotation): Add highlight annotation

CHANGELOG.md, src/annotations/AnnotationLayer.tsx, src/annotations/AnnotationType.ts, src/annotations/StrikeOut.tsx
=> feat(annotation): Add strikeout annotation

CHANGELOG.md, src/annotations/AnnotationLayer.tsx, src/annotations/AnnotationType.ts, src/annotations/Squiggly.tsx
=> feat(annotation): Add squiggly annotation

CHANGELOG.md, demo/latest/src/App.tsx, src/annotations/AnnotationLayer.tsx, src/annotations/Link.tsx, src/layers/PageLayer.tsx, src/layouts/Inner.tsx, src/vendors/PdfJs.d.ts
=> feat(annotation): Support named actions

CHANGELOG.md, src/annotations/Link.tsx, src/vendors/PdfJs.d.ts
=> feat(annotation): Support external links

src/annotations/Text.tsx, src/icons/CommentIcon.tsx, src/icons/HelpIcon.tsx, src/icons/KeyIcon.tsx, src/icons/NoteIcon.tsx, src/icons/ParagraphIcon.tsx, src/icons/TriangleIcon.tsx, src/vendors/PdfJs.d.ts
=> Add icons for text annotation if needed

src/annotations/AnnotationLayer.tsx, src/annotations/PopupWrapper.tsx
=> fix(annotation): Break new line in annotation content

src/annotations/Annotation.tsx, src/annotations/Ink.tsx, src/annotations/Text.tsx, src/vendors/PdfJs.d.ts
=> feat(annotation): Add svg polyline to ink annotation

CHANGELOG.md, src/annotations/AnnotationLayer.tsx, src/annotations/AnnotationType.ts, src/annotations/Caret.tsx
=> feat(annotation): Add caret annotation

CHANGELOG.md, src/annotations/AnnotationLayer.tsx, src/annotations/AnnotationType.ts, src/annotations/Polyline.tsx, src/vendors/PdfJs.d.ts
=> feat(annotation): Add polyline annotation

CHANGELOG.md, src/annotations/AnnotationLayer.tsx, src/annotations/AnnotationType.ts, src/annotations/Polygon.tsx
=> feat(annotation): Add polygon annotation

CHANGELOG.md, src/annotations/AnnotationLayer.tsx, src/annotations/AnnotationType.ts, src/annotations/FileAttachment.tsx, src/vendors/PdfJs.d.ts
=> feat(annotation): Add file attachment annotation

CHANGELOG.md, src/Viewer.tsx
=> feat: Allow to control fileUrl

demo/linkify/FindLinkExample.tsx, demo/linkify/LinkifyWrapper.tsx, demo/linkify/README.md
for https://github.com/phuoc-ng/react-pdf-viewer/issues/129#issuecomment-624119082
=> Add linkify example

CHANGELOG.md, demo/store-current-page/StoreCurrentPageExample.tsx, dist/index.d.ts, src/Viewer.tsx, src/layouts/Inner.tsx
=> Add onPageChange option 

.eslintrc
=> Fix lint command

CHANGELOG.md, demo/draw-canvas/DrawCanvasExample.tsx, dist/index.d.ts, src/Viewer.tsx, src/layers/CanvasLayer.tsx, src/layers/PageLayer.tsx, src/layouts/Inner.tsx
=> feat: Add new event invoked when canvas is rendered

packages/rpv-current-page/src/CurrentPageLabel.tsx, packages/rpv-current-page/src/StoreProps.ts, packages/rpv-current-page/src/index.tsx
=> Add props render for current page plugin

packages/rpv-first-page/.gitignore, packages/rpv-first-page/npm/index.d.ts, packages/rpv-first-page/package.json, packages/rpv-first-page/rollup.config.js, packages/rpv-first-page/src/GoToFirstPage.tsx, packages/rpv-first-page/src/GoToFirstPageButton.tsx, packages/rpv-first-page/src/StoreProps.ts, packages/rpv-first-page/src/UpArrowIcon.tsx, packages/rpv-first-page/src/firstPagePlugin.tsx, packages/rpv-first-page/src/index.ts, packages/rpv-first-page/tsconfig.json
=> Add plugin to go to the first page

packages/rpv-first-page/src/index.d.ts, packages/rpv-first-page/src/index.ts, packages/rpv-last-page/.gitignore, packages/rpv-last-page/dist/index.js, packages/rpv-last-page/package.json, packages/rpv-last-page/rollup.config.js, packages/rpv-last-page/src/DownArrowIcon.tsx, packages/rpv-last-page/src/GoToLastPage.tsx, packages/rpv-last-page/src/GoToLastPageButton.tsx, packages/rpv-last-page/src/StoreProps.ts, packages/rpv-last-page/src/index.d.ts, packages/rpv-last-page/src/index.ts, packages/rpv-last-page/src/lastPagePlugin.tsx, packages/rpv-last-page/tsconfig.json, packages/rpv-toolbar/package.json, packages/rpv-toolbar/src/ToolbarSlot.ts, packages/rpv-toolbar/src/defaultToolbar.tsx, packages/rpv-toolbar/src/toolbarPlugin.tsx
=> Add last-page plugin

packages/rpv-full-screen/src/fullScreenPlugin.tsx, packages/rpv-toolbar/src/toolbarPlugin.tsx, packages/rpv/src/index.d.ts, packages/rpv/src/index.ts, packages/rpv/src/layouts/Inner.tsx, packages/rpv/src/layouts/Slot.ts, packages/rpv/src/types/Plugin.ts
=> Change renderBody signature

packages/rpv-toolbar/src/ToolbarSlot.ts, packages/rpv-toolbar/src/defaultToolbar.tsx, packages/rpv-toolbar/src/index.d.ts, packages/rpv-toolbar/src/toolbarPlugin.tsx, packages/rpv-zoom/src/CurrentScale.tsx, packages/rpv-zoom/src/index.d.ts, packages/rpv-zoom/src/zoomPlugin.tsx
=> Add current scale

packages/rpv-page-navigation/src/CurrentPageInput.tsx, packages/rpv-page-navigation/src/CurrentPageLabel.tsx, packages/rpv-page-navigation/src/DownArrowIcon.tsx, packages/rpv-page-navigation/src/GoToFirstPage.tsx, packages/rpv-page-navigation/src/GoToFirstPageButton.tsx, packages/rpv-page-navigation/src/GoToLastPage.tsx, packages/rpv-page-navigation/src/GoToLastPageButton.tsx, packages/rpv-page-navigation/src/NextIcon.tsx, packages/rpv-page-navigation/src/NextPageButton.tsx, packages/rpv-page-navigation/src/PreviousIcon.tsx, packages/rpv-page-navigation/src/PreviousPageButton.tsx, packages/rpv-page-navigation/src/UpArrowIcon.tsx, packages/rpv-page-navigation/src/index.d.ts, packages/rpv-page-navigation/src/index.ts, packages/rpv-page-navigation/src/useCurrentPage.ts, packages/rpv-page-navigation/src/useNumberOfPages.ts, packages/rpv-toolbar/src/toolbarPlugin.tsx, packages/rpv/src/index.d.ts, packages/rpv/src/index.ts
=> Navigation hook

packages/rpv-toolbar/src/ToolbarSlot.ts, packages/rpv-toolbar/src/defaultToolbar.tsx, packages/rpv-toolbar/src/index.d.ts, packages/rpv-toolbar/src/toolbarPlugin.tsx, packages/rpv-zoom/src/CurrentScale.tsx, packages/rpv-zoom/src/ZoomIn.tsx, packages/rpv-zoom/src/ZoomOut.tsx, packages/rpv-zoom/src/index.d.ts, packages/rpv-zoom/src/index.ts
=> Zoom in/out slots in toolbar

packages/rpv-download/src/Download.tsx, packages/rpv-download/src/index.d.ts, packages/rpv-download/src/index.ts, packages/rpv-full-screen/src/EnterFullScreen.tsx, packages/rpv-full-screen/src/index.d.ts, packages/rpv-full-screen/src/index.ts, packages/rpv-open/src/Open.tsx, packages/rpv-open/src/OpenButton.tsx, packages/rpv-open/src/index.d.ts, packages/rpv-open/src/index.ts, packages/rpv-open/src/openButton.less, packages/rpv-open/src/openPlugin.tsx, packages/rpv-print/src/Print.tsx, packages/rpv-print/src/index.d.ts, packages/rpv-print/src/index.ts, packages/rpv-toolbar/src/ToolbarSlot.ts, packages/rpv-toolbar/src/defaultToolbar.tsx, packages/rpv-toolbar/src/index.d.ts, packages/rpv-toolbar/src/toolbarPlugin.tsx
=> Change signature of toolbar slot

packages/rpv-page-navigation/src/GoToFirstPageMenuItem.tsx, packages/rpv-page-navigation/src/GoToLastPage.tsx, packages/rpv-page-navigation/src/GoToLastPageMenuItem.tsx, packages/rpv-page-navigation/src/index.d.ts, packages/rpv-page-navigation/src/index.ts, packages/rpv-page-navigation/src/pageNavigationPlugin.tsx, packages/rpv-page-navigation/src/useCurrentPage.ts, packages/rpv-page-navigation/src/useNumberOfPages.ts, packages/rpv-toolbar/src/MoreActionsPopover.tsx, packages/rpv-toolbar/src/MoreIcon.tsx, packages/rpv-toolbar/src/ToolbarSlot.ts, packages/rpv-toolbar/src/defaultToolbar.tsx, packages/rpv-toolbar/src/index.d.ts, packages/rpv-toolbar/src/toolbarPlugin.tsx, packages/rpv/src/layouts/MoreActionsPopover.tsx, packages/rpv/src/layouts/Toolbar.tsx
=> Move going to first/last pages to more actions popover

packages/rpv-scroll-mode/src/index.d.ts, packages/rpv-scroll-mode/src/index.ts, packages/rpv-scroll-mode/src/scrollModePlugin.tsx, packages/rpv-toolbar/src/ToolbarSlot.ts, packages/rpv-toolbar/src/index.d.ts
=> Correct type for SwitchScrollModeMenuItemProps

demo/latest/src/App.tsx, packages/rpv-search/src/index.d.ts, packages/rpv-search/src/index.ts, packages/rpv-search/src/searchPlugin.tsx, packages/rpv-selection-mode/src/index.d.ts, packages/rpv-selection-mode/src/index.ts, packages/rpv-selection-mode/src/selectionModePlugin.tsx, packages/rpv-toolbar/src/index.d.ts, packages/rpv-toolbar/src/toolbarPlugin.tsx
=> Group plugin options

demo/latest/src/App.tsx, packages/rpv-download/README.md, packages/rpv-download/src/Download.tsx, packages/rpv-download/src/downloadFile.ts, packages/rpv-download/src/downloadPlugin.tsx, packages/rpv-download/src/getFileName.ts, packages/rpv-download/src/index.d.ts, packages/rpv-download/src/index.ts, packages/rpv-toolbar/src/index.d.ts, packages/rpv-toolbar/src/toolbarPlugin.tsx
=> Download options

packages/rpv-bookmark/src/BookmarkLoader.tsx
=> Reload bookmarks when the doc is changed

packages/rpv/src/layouts/Inner.tsx
=> Can't jump to destination bookmark when called from plugin

packages/core/src/annotations/annotation.less, packages/core/src/annotations/link.less, packages/core/src/annotations/popupWrapper.less, packages/core/src/components/button.less, packages/core/src/components/menu.less, packages/core/src/components/menuDivider.less, packages/core/src/components/menuItem.less, packages/core/src/components/primaryButton.less, packages/core/src/components/progressBar.less, packages/core/src/components/separator.less, packages/core/src/components/spinner.less, packages/core/src/icons/icon.less, packages/core/src/layers/canvasLayer.less, packages/core/src/layers/pageLayer.less, packages/core/src/layers/textLayer.less, packages/core/src/layouts/inner.less, packages/core/src/layouts/pageSizeCalculator.less, packages/core/src/loader/askingPassword.less, packages/core/src/loader/documentLoader.less, packages/core/src/portal/arrow.less, packages/core/src/portal/modalBody.less, packages/core/src/portal/modalOverlay.less, packages/core/src/portal/popoverBody.less, packages/core/src/portal/popoverOverlay.less, packages/core/src/portal/tooltipBody.less, packages/core/src/theme/ThemeContext.ts, packages/core/src/theme/ThemeProvider.tsx, packages/core/src/theme/common.less
=> Change prefix of core components

demo/latest/src/App.tsx, demo/latest/webpack.config.js, packages/default-layout/src/styles/index.ts, packages/toolbar/src/styles/index.ts
=> Import the main entry point of styles

packages/drop/src/dropPlugin.tsx
=> fix(drop): The drop area should take full width

packages/properties/src/ShowProperties.tsx, packages/properties/src/ShowPropertiesButton.tsx, packages/properties/src/ShowPropertiesMenuItem.tsx, packages/properties/src/index.d.ts
=> Remove icon and label from render prop

packages/properties/src/index.d.ts, packages/properties/src/propertiesPlugin.tsx
=> Add default button to show document properties

demo/latest/src/App.tsx, packages/selection-mode/src/index.d.ts, packages/selection-mode/src/selectionModePlugin.tsx
=> Add default button to switch selection mode

packages/scroll-mode/src/index.d.ts, packages/scroll-mode/src/scrollModePlugin.tsx
=> Add default button to switch scroll mode

packages/core/src/layouts/Inner.tsx, packages/scroll-mode/src/Tracker.tsx, packages/scroll-mode/src/index.d.ts, packages/scroll-mode/src/scrollModePlugin.tsx, packages/toolbar/src/index.d.ts, packages/toolbar/src/toolbarPlugin.tsx
=> feat(scroll-mode): Initial scroll mode

packages/search/src/ShowSearchPopover.tsx, packages/search/src/ShowSearchPopoverButton.tsx, packages/search/src/ShowSearchPopoverDecorator.tsx, packages/search/src/index.d.ts, packages/search/src/searchPlugin.tsx
=> Add default button to show search popover

packages/search/src/index.d.ts
=> Remove unnecessary options to render search popover

demo/latest/package.json, demo/latest/src/App.tsx, packages/default-layout/src/defaultLayoutPlugin.tsx, packages/default-layout/src/index.d.ts, packages/toolbar/src/index.d.ts, packages/toolbar/src/index.ts
=> feat(default-layout): Customize toolbar renderer

CHANGELOG.md, demo/latest/src/App.tsx, packages/core/src/Viewer.tsx, packages/core/src/index.d.ts, packages/core/src/loader/DocumentLoader.tsx, packages/core/src/vendors/PdfJs.d.ts
=> feat(core): Custom loader

CHANGELOG.md, demo/src/App.tsx, packages/search/src/SearchPopover.tsx
=> Clicking Previous match or Next match button throws an error if keyword is empty

CHANGELOG.md, demo/src/App.tsx, lerna.json, packages/core/src/annotations/AnnotationLayer.tsx, packages/core/src/annotations/AnnotationLayerBody.tsx, packages/core/src/annotations/AnnotationLoader.tsx, packages/core/src/index.d.ts, packages/core/src/index.ts, packages/core/src/layers/PageLayer.tsx, packages/core/src/types/Plugin.ts
=> feat(core): Custom hook on annotation render

CHANGELOG.md, demo/src/App.tsx, packages/search/src/Tracker.tsx, packages/search/src/styles/highlight.less
=> feat(search): Doesn't perform unhighligting and highlighting many times after texts rendered

CHANGELOG.md, demo/src/App.tsx, packages/search/src/SearchPopover.tsx, packages/search/src/StoreProps.ts, packages/search/src/Tracker.tsx, packages/search/src/index.d.ts, packages/search/src/searchPlugin.tsx
=> feat(search): Allow to set multiple keywords

CHANGELOG.md, packages/default-layout/src/defaultLayoutPlugin.tsx
=> fix(default-layout): The print plugin doesn't work with default-layout plugin

CHANGELOG.md, packages/print/src/styles/printZone.less
=> fix(print): In some cases, there is an extra blank page when printing

packages/search/src/SearchPopover.tsx, packages/search/src/useSearch.ts
=> feat(search): Move search logics to external hook

CHANGELOG.md, demo/package.json, demo/src/App.tsx, demo/src/index.html, packages/search/src/Search.tsx, packages/search/src/index.d.ts, packages/search/src/searchPlugin.tsx, packages/toolbar/src/ToolbarSlot.ts, packages/toolbar/src/index.d.ts, packages/toolbar/src/toolbarPlugin.tsx
=> feat(search): Custom search control

CHANGELOG.md, demo/src/App.tsx, packages/core/src/layouts/Inner.tsx
=> fix(core): Clicking bookmark doesn't jump to correct page in horizontal scroll mode

CHANGELOG.md, demo/src/App.tsx, demo/src/styles.css, packages/search/src/Tracker.tsx
=> feat(search): Add a class to current match

CHANGELOG.md, demo/package.json, demo/src/App.tsx, packages/bookmark/src/BookmarkListWithStore.tsx, packages/bookmark/src/StoreProps.ts, packages/core/src/annotations/AnnotationLayer.tsx, packages/core/src/annotations/AnnotationLayerBody.tsx, packages/core/src/annotations/Link.tsx, packages/core/src/index.d.ts, packages/core/src/layers/PageLayer.tsx, packages/core/src/layouts/Inner.tsx, packages/core/src/types/PluginFunctions.ts, packages/search/src/StoreProps.ts, packages/search/src/Tracker.tsx
=> fix(search): Jumping between search match doesn't work properly in horizontal scroll

CHANGELOG.md, packages/core/src/layers/CanvasLayer.tsx, packages/core/src/styles/inner.less
=> fix(core): Avoid the black flickering when clicking a bookmark

CHANGELOG.md, packages/core/src/Viewer.tsx, packages/core/src/index.d.ts, packages/core/src/index.ts, packages/core/src/layers/CanvasLayer.tsx, packages/core/src/layers/PageLayer.tsx, packages/core/src/layers/TextLayer.tsx, packages/core/src/layouts/Inner.tsx, packages/core/src/types/LayerRenderStatus.ts, packages/core/src/types/Plugin.ts, packages/search/src/Tracker.tsx
=> feat(core): Move onCanvasLayerRender option to plugin

CHANGELOG.md, demo/package.json, packages/attachment/package.json, packages/bookmark/package.json, packages/core/package.json, packages/default-layout/package.json, packages/drop/package.json, packages/full-screen/package.json, packages/get-file/package.json, packages/locale-switcher/package.json, packages/open/package.json, packages/page-navigation/package.json, packages/print/package.json, packages/properties/package.json, packages/rotate/package.json, packages/scroll-mode/package.json, packages/search/package.json, packages/selection-mode/package.json, packages/thumbnail/package.json, packages/toolbar/package.json, packages/zoom/package.json
=> feat: Support both React v16 and v17

CHANGELOG.md, package.json, packages/core/src/layers/PageLayer.tsx, packages/core/src/layouts/Inner.tsx
=> feat(core): Prerender pages

demo/src/App.tsx, packages/highlight/src/HighlightArea.ts, packages/highlight/src/SelectionRange.ts, packages/highlight/src/SelectionState.ts, packages/highlight/src/StoreProps.ts, packages/highlight/src/Tracker.tsx, packages/highlight/src/getRectFromOffsets.ts, packages/highlight/src/getTextFromOffsets.ts, packages/highlight/src/highlightPlugin.tsx
=> Track the selection state and selected text

demo/src/App.tsx, packages/core/src/index.d.ts, packages/core/src/layers/PageLayer.tsx, packages/core/src/types/Plugin.ts, packages/highlight/src/HighlightAreaList.tsx, packages/highlight/src/RenderHighlightTarget.ts, packages/highlight/src/SelectionData.ts, packages/highlight/src/SelectionState.ts, packages/highlight/src/Tracker.tsx, packages/highlight/src/highlightPlugin.tsx, packages/highlight/src/index.d.ts
=> Be able to render highlighting trigger element

demo/src/App.tsx, package.json, packages/highlight/package.json, packages/highlight/postcss.config.js, packages/highlight/src/HighlightAreaList.tsx, packages/highlight/src/RenderHighlightTargetProps.ts, packages/highlight/src/SelectionState.ts, packages/highlight/src/Tracker.tsx, packages/highlight/src/constants.ts, packages/highlight/src/highlightPlugin.tsx, packages/highlight/src/index.d.ts, packages/highlight/src/styles/highlighting.less, packages/highlight/src/styles/index.ts
=> fix(highlight): Fix the position of mark

demo/src/App.tsx, packages/highlight/src/HighlightAreaList.tsx, packages/highlight/src/RenderHighlightContentProps.ts, packages/highlight/src/getTextFromOffsets.ts, packages/highlight/src/highlightPlugin.tsx, packages/highlight/src/index.d.ts
=> feat(highlight): Render content

demo/src/App.tsx, packages/highlight/src/MessageIcon.tsx, packages/highlight/src/Tracker.tsx, packages/highlight/src/index.d.ts, packages/highlight/src/index.ts
=> feat(highlight): Add message icon

demo/src/App.tsx, packages/highlight/src/highlightPlugin.tsx
=> fix(highlight): Fix issue that the store is recreated

demo/src/App.tsx
=> feat(highlight): Clear the highlights when the document is changed

demo/src/App.tsx, packages/highlight/src/HighlightAreaList.tsx, packages/highlight/src/HighlightRect.tsx, packages/highlight/src/StoreProps.ts, packages/highlight/src/Tracker.tsx, packages/highlight/src/getCssProperties.ts, packages/highlight/src/highlightPlugin.tsx, packages/highlight/src/index.d.ts, packages/highlight/src/styles/rect.less, packages/highlight/src/transformArea.ts, packages/highlight/src/types/RenderHighlightsProps.ts, packages/highlight/src/useRotation.ts
=> feat(highlight): Support rotating the document

CHANGELOG.md, demo/src/App.tsx, packages/default-layout/src/Sidebar.tsx, packages/default-layout/src/defaultLayoutPlugin.tsx, packages/default-layout/src/index.d.ts
=> feat(default-layout): Customize sidebar tabs

demo/src/App.tsx
=> feat(highlight): List notes in the sidebar

configs/setupTests.ts, jest.config.js, package.json, packages/core/__tests__/viewer.spec.tsx, packages/core/package.json, tsconfig.json
=> Setup test and the first simple test

packages/core/src/layouts/Inner.tsx
=> fix(core): Fix incorrect useRef

demo/src/App.tsx, packages/core/src/loader/DocumentLoader.tsx, packages/highlight/src/transformArea.ts
=> feat(highlight): Add sample notes

CHANGELOG.md, packages/highlight/package.json
=> fix(highlight): The styles are missing in the highlight plugin

CHANGELOG.md, packages/core/src/annotations/AnnotationLayerBody.tsx, packages/core/src/annotations/Highlight.tsx
=> fix(core): The popup annotations aren't shown if they are children of highlight annotations

CHANGELOG.md, demo/package.json, demo/src/App.tsx, packages/full-screen/src/EnterFullScreen.tsx, packages/full-screen/src/ExitFullScreenButton.tsx, packages/full-screen/src/fullScreenPlugin.tsx, packages/full-screen/src/index.d.ts, packages/full-screen/src/types.ts, packages/toolbar/src/index.d.ts, packages/toolbar/src/toolbarPlugin.tsx
=> feat(full-screen): Fullscreen callbacks

packages/core/src/hooks/useIsMounted.ts, packages/core/src/loader/DocumentLoader.tsx, packages/core/src/vendors/PdfJs.d.ts
=> Fix unmount and worker issues

CHANGELOG.md, packages/core/src/Viewer.tsx, packages/core/src/hooks/useIntersectionObserver.ts, packages/core/src/hooks/usePrevious.ts, packages/core/src/index.d.ts, packages/core/src/index.ts, packages/core/src/layers/PageLayer.tsx, packages/thumbnail/src/ThumbnailContainer.tsx
=> feat(core): Lazy load the document

CHANGELOG.md, demo/src/App.tsx, packages/default-layout/src/defaultLayoutPlugin.tsx, packages/default-layout/src/index.d.ts, packages/toolbar/src/index.d.ts, packages/toolbar/src/toolbarPlugin.tsx
=> feat: Access plugin instances

CHANGELOG.md, demo/src/App.tsx, packages/search/src/index.d.ts, packages/search/src/searchPlugin.tsx
=> feat(search): Highlight keywords programatically

CHANGELOG.md, demo/src/App.tsx, packages/zoom/src/index.d.ts, packages/zoom/src/zoomPlugin.tsx
=> feat(zoom): Expose the zoom function

CHANGELOG.md, demo/src/App.tsx, packages/page-navigation/src/index.d.ts, packages/page-navigation/src/pageNavigationPlugin.tsx, packages/toolbar/src/index.d.ts
=> feat(page-navigation): Expose API to jump to given page

demo/webpack.config.js
=> Webpack setting to replace pdfjs-dist with signature patch

CHANGELOG.md, demo/src/App.tsx, packages/search/src/Tracker.tsx
=> fix(search): The Search plugin can find text that belongs to multiple span elements

demo/src/App.tsx, packages/search/src/Tracker.tsx
=> fix(search): Character indexes preparation must be put at the top

.gitignore, packages/core/__tests__/Viewer.test.tsx, packages/core/package.json, test-utils/mockIntersectionObserver.ts
=> Test cases for Viewer

packages/core/__tests__/Viewer.test.tsx, packages/core/src/Viewer.tsx, test-utils/mockIntersectionObserver.ts
=> feat(core): Test lazy load

packages/core/__tests__/Viewer.test.tsx, packages/core/src/layers/PageLayer.tsx
=> feat(core): Test lazy load page

packages/core/src/annotations/Popup.tsx, packages/core/src/hooks/useIntersectionObserver.ts, packages/core/src/hooks/useIsomorphicLayoutEffect.ts, packages/core/src/hooks/usePosition.ts, packages/core/src/index.d.ts, packages/core/src/index.ts, packages/core/src/layers/WithScale.tsx, packages/page-navigation/src/useCurrentPage.ts, packages/thumbnail/src/ThumbnailListWithStore.tsx
=> Layout effect

demo/package.json, packages/zoom/__tests__/zoom.test.tsx, packages/zoom/package.json
=> feat(zoom): Test zoom() API

CHANGELOG.md, demo/src/App.tsx, packages/core/src/hooks/useIsomorphicLayoutEffect.ts, packages/core/src/index.d.ts, packages/page-navigation/src/useCurrentPage.ts, packages/search/src/Tracker.tsx, packages/search/src/index.d.ts, packages/search/src/searchPlugin.tsx, packages/search/src/types/OnHighlightKeyword.ts
=> feat(search): Highlight callback

packages/search/__tests__/keyword.test.tsx, packages/search/__tests__/keywordMultipleSpans.test.tsx, packages/search/__tests__/onHighlightKeyword.test.tsx, packages/search/package.json, packages/search/src/Tracker.tsx
=> More test cases for search plugin

packages/search/src/Search.tsx, packages/search/src/SearchPopover.tsx, packages/search/src/ShowSearchPopover.tsx, packages/search/src/useSearch.ts
=> chore(search): Some refactoring

CHANGELOG.md, demo/src/App.tsx, packages/search/src/index.d.ts, packages/search/src/normalizeKeyword.ts, packages/search/src/searchPlugin.tsx, packages/search/src/useSearch.ts
for #451 
https://user-images.githubusercontent.com/57786711/107506546-cc4e8680-6bd0-11eb-9203-02323103982a.mp4
=> feat(search): Jump between matches API

packages/search/__tests__/clearHighlights.test.tsx, packages/search/__tests__/highlight.test.tsx
=> Test cases for highlight API

CHANGELOG.md, packages/get-file/src/Download.tsx
=> fix(get-file): Clicking the Download button doesn't work

CHANGELOG.md, packages/open/src/styles/openButton.less
for #477 
https://user-images.githubusercontent.com/57786711/110244880-6963cb80-7f93-11eb-8d06-8707bb6b9b4a.mp4
=> fix(open): The Open file button covers other elements

CHANGELOG.md, demo/src/App.tsx, packages/zoom/src/ShortcutHandler.tsx, packages/zoom/src/zoomPlugin.tsx
=> feat(zoom): Add shortcuts for zooming

demo/src/App.tsx, packages/print/src/ShortcutHandler.tsx, packages/zoom/src/ShortcutHandler.tsx
=> Handle cmd key properly

CHANGELOG.md, packages/get-file/src/downloadFile.ts
=> fix(download): Can't open the downloaded file if it was loaded with Uint8Array

CHANGELOG.md, demo/src/App.tsx, packages/core/src/annotations/PopupWrapper.tsx
fix #509 
https://user-images.githubusercontent.com/57786711/115958523-f0fc9e00-a531-11eb-814c-e88cf9e30fbd.mp4
=> fix: Annotation popup can be displayed under the previous or next page

CHANGELOG.md, packages/core/src/utils/isSameUrl.ts, packages/get-file/src/downloadFile.ts, packages/print/src/PageThumbnail.tsx, packages/print/src/PageThumbnailContainer.tsx, packages/print/src/PrintContainer.tsx, packages/print/src/PrintProgress.tsx, packages/print/src/PrintZone.tsx
=> feat(print): Display the progress properly when printing a big document

CHANGELOG.md, packages/print/src/PageThumbnail.tsx, packages/print/src/PageThumbnailContainer.tsx, packages/print/src/PrintZone.tsx, packages/print/src/styles/printZone.less
=> feat(print): Use a shared canvas

CHANGELOG.md, README.md, packages/attachment/src/styles/attachmentList.less, packages/bookmark/src/styles/bookmarkList.less, packages/bookmark/src/styles/bookmarkLoaded.less, packages/default-layout/src/styles/sidebar.less, packages/thumbnail/src/ThumbnailContainer.tsx, packages/thumbnail/src/ThumbnailList.tsx, packages/thumbnail/src/scrollToBeVisible.ts, packages/thumbnail/src/styles/thumbnailList.less
=> feat(thumbnails): Automatically scroll to the thumbnail that represents the current page

CHANGELOG.md, packages/core/src/layers/CanvasLayer.tsx, packages/core/src/styles/canvasLayer.less
=> feat(core): Keep showing a spinner until the canvas layer is rendered completely

CHANGELOG.md, packages/get-file/src/DownloadMenuItem.tsx, packages/get-file/src/getFilePlugin.tsx, packages/get-file/src/index.d.ts, packages/toolbar/src/ToolbarSlot.ts, packages/toolbar/src/index.d.ts, packages/toolbar/src/toolbarPlugin.tsx
=> feat(get-file): Add download menu item

CHANGELOG.md, packages/full-screen/src/index.d.ts, packages/print/src/PrintMenuItem.tsx, packages/print/src/index.d.ts, packages/print/src/printPlugin.tsx, packages/toolbar/src/ToolbarSlot.ts, packages/toolbar/src/index.d.ts, packages/toolbar/src/toolbarPlugin.tsx
=> feat(print): Add print menu item

CHANGELOG.md, packages/open/src/Open.tsx, packages/open/src/OpenButton.tsx, packages/open/src/OpenMenuItem.tsx, packages/open/src/index.d.ts, packages/open/src/openPlugin.tsx, packages/open/src/styles/index.less, packages/open/src/styles/openInput.less, packages/open/src/styles/openMenuItem.less, packages/toolbar/src/MoreActionsPopover.tsx, packages/toolbar/src/ToolbarSlot.ts, packages/toolbar/src/index.d.ts, packages/toolbar/src/toolbarPlugin.tsx
=> feat(open): Add open menu item

CHANGELOG.md, packages/page-navigation/src/GoToPreviousPageMenuItem.tsx, packages/page-navigation/src/index.d.ts, packages/page-navigation/src/pageNavigationPlugin.tsx, packages/toolbar/src/MoreActionsPopover.tsx, packages/toolbar/src/ToolbarSlot.ts, packages/toolbar/src/toolbarPlugin.tsx
=> feat(page-navigation): Add menu item to go to the previous page

CHANGELOG.md, packages/page-navigation/src/GoToNextPageMenuItem.tsx, packages/page-navigation/src/index.d.ts, packages/page-navigation/src/pageNavigationPlugin.tsx, packages/toolbar/src/ToolbarSlot.ts, packages/toolbar/src/index.d.ts, packages/toolbar/src/toolbarPlugin.tsx
=> feat(page-navigation): Add new menu item to go to the next page

CHANGELOG.md, packages/core/src/components/MenuItem.tsx, packages/core/src/index.d.ts, packages/core/src/styles/menuItem.less, packages/page-navigation/src/GoToNextPageMenuItem.tsx, packages/page-navigation/src/GoToPreviousPageMenuItem.tsx, packages/page-navigation/src/index.d.ts, packages/page-navigation/src/pageNavigationPlugin.tsx, packages/toolbar/src/MoreActionsPopover.tsx, packages/toolbar/src/ToolbarSlot.ts, packages/toolbar/src/index.d.ts
=> feat(core): Add disabled state for menu

CHANGELOG.md, packages/core/src/components/Button.tsx, packages/core/src/index.d.ts, packages/core/src/styles/button.less, packages/page-navigation/src/GoToFirstPage.tsx, packages/page-navigation/src/GoToFirstPageButton.tsx, packages/page-navigation/src/GoToFirstPageMenuItem.tsx, packages/page-navigation/src/GoToLastPage.tsx, packages/page-navigation/src/GoToLastPageButton.tsx, packages/page-navigation/src/GoToLastPageMenuItem.tsx, packages/page-navigation/src/GoToNextPage.tsx, packages/page-navigation/src/GoToNextPageButton.tsx, packages/page-navigation/src/GoToNextPageMenuItem.tsx, packages/page-navigation/src/GoToPreviousPage.tsx, packages/page-navigation/src/GoToPreviousPageButton.tsx, packages/page-navigation/src/GoToPreviousPageMenuItem.tsx, packages/page-navigation/src/index.d.ts, packages/page-navigation/src/pageNavigationPlugin.tsx, packages/page-navigation/src/types/index.ts, packages/toolbar/src/ToolbarSlot.ts, packages/toolbar/src/index.d.ts
=> feat(core): Add disabled state for button

CHANGELOG.md, packages/core/src/styles/icon.less
=> feat(core): The icons use the current color

CHANGELOG.md, packages/toolbar/src/MoreActionsPopover.tsx, packages/toolbar/src/ToolbarSlot.ts, packages/toolbar/src/index.d.ts, packages/toolbar/src/toolbarPlugin.tsx, packages/zoom/src/ZoomInMenuItem.tsx, packages/zoom/src/ZoomOutMenuItem.tsx, packages/zoom/src/index.d.ts, packages/zoom/src/types/index.ts, packages/zoom/src/zoomPlugin.tsx
=> feat(zoom): Add new menu items for zooming

CHANGELOG.md, packages/core/src/portal/ModalBody.tsx, packages/core/src/portal/PopoverBody.tsx, packages/core/src/styles/modalBody.less, packages/core/src/styles/modalOverlay.less, packages/core/src/styles/utils.less, packages/default-layout/src/styles/defaultLayout.less, packages/properties/src/styles/propertiesModal.less, packages/properties/src/styles/propertyItem.less, packages/toolbar/src/defaultToolbar.tsx
=> feat(default-layout): Tweak on small screens

CHANGELOG.md, packages/core/src/layouts/PageSizeCalculator.tsx
=> fix(core): Zoom the document best inside the container initially

CHANGELOG.md, packages/bookmark/src/BookmarkLoader.tsx, packages/bookmark/src/styles/bookmarkList.less, packages/bookmark/src/styles/bookmarkLoaded.less
=> fix(bookmark): Some bookmarks are hidden initially

CHANGELOG.md, demo/src/App.tsx, packages/core/src/Viewer.tsx, packages/core/src/index.d.ts, packages/core/src/loader/DocumentLoader.tsx
=> feat(core): Add transformGetDocumentParams option

CHANGELOG.md, packages/print/src/ShortcutHandler.tsx, packages/zoom/src/ShortcutHandler.tsx
=> fix: Doesn't work with NextJS because navigator isn't defined

CHANGELOG.md, packages/core/src/Viewer.tsx, packages/core/src/index.d.ts
=> feat(core): Add new theme option

packages/core/src/Viewer.tsx, packages/core/src/index.d.ts, packages/core/src/index.ts, packages/core/src/theme/ThemeContext.tsx, packages/core/src/theme/ThemeProvider.tsx
=> feat(core): Add theme provider

CHANGELOG.md, packages/core/src/Viewer.tsx, packages/core/src/index.d.ts, packages/core/src/theme/ThemeContext.tsx, packages/core/src/theme/ThemeProvider.tsx, packages/open/src/OpenMenuItem.tsx, packages/theme/dist/index.js, packages/theme/package.json, packages/theme/src/DarkIcon.tsx, packages/theme/src/LightIcon.tsx, packages/theme/src/SwitchTheme.tsx, packages/theme/src/SwitchThemeButton.tsx, packages/theme/src/SwitchThemeMenuItem.tsx, packages/theme/src/index.d.ts, packages/theme/src/index.ts, packages/theme/src/themePlugin.tsx, packages/theme/tsconfig.json, packages/toolbar/package.json, packages/toolbar/src/MoreActionsPopover.tsx, packages/toolbar/src/ToolbarSlot.ts, packages/toolbar/src/defaultToolbar.tsx, packages/toolbar/src/index.d.ts, packages/toolbar/src/toolbarPlugin.tsx
for #582 #273 
https://user-images.githubusercontent.com/57786711/120893819-63879000-c63f-11eb-8ef9-7eb6c7f64014.mp4
=> feat: New theme plugin

CHANGELOG.md, demo/src/App.tsx, packages/core/src/theme/ThemeProvider.tsx, packages/core/src/utils/isDarkMode.ts
=> feat(core): Be able to switch to dark/light theme automatically

packages/bookmark/src/styles/theme.less, packages/core/src/styles/popoverBody.less, packages/core/src/styles/textBox.less, packages/core/src/styles/theme.less, packages/default-layout/src/styles/theme.less, packages/drop/src/styles/theme.less, packages/print/src/styles/theme.less
=> Tweak dark theme

CHANGELOG.md, packages/core/src/styles/menuItem.less
=> fix(core): Icons in menu items aren't centered horizontally

CHANGELOG.md, packages/search/src/useSearch.ts
=> fix(search): Jump to the next or previous match if the keyword isn't found

CHANGELOG.md, demo/src/App.tsx, packages/core/src/layers/TextLayer.tsx, packages/core/src/styles/textLayer.less, packages/core/src/styles/theme.less, packages/core/src/vendors/PdfJs.d.ts, packages/highlight/src/highlightPlugin.tsx, packages/highlight/src/styles/selectedText.less
=> feat(highlight): Improve text selection

CHANGELOG.md, packages/bookmark/src/BookmarkItem.tsx, packages/core/src/annotations/AnnotationLayer.tsx, packages/core/src/annotations/PopupWrapper.tsx, packages/core/src/layers/CanvasLayer.tsx, packages/core/src/layers/SvgLayer.tsx, packages/core/src/layers/TextLayer.tsx, packages/core/src/portal/ModalBody.tsx, packages/core/src/portal/Popover.tsx, packages/core/src/portal/PopoverBody.tsx, packages/core/src/portal/Tooltip.tsx, packages/core/src/portal/TooltipBody.tsx
=> Use useRef to keep the ref instance

CHANGELOG.md, demo/src/App.tsx, packages/core/src/Viewer.tsx, packages/core/src/theme/ThemeContext.tsx, packages/core/src/theme/ThemeProvider.tsx, packages/theme/src/SwitchTheme.tsx
=> Treat light theme as the default

CHANGELOG.md, packages/print/src/PrintZone.tsx
=> fix(print): Can't open any popover after printing

CHANGELOG.md, demo/package.json, packages/toolbar/package.json, packages/toolbar/src/index.d.ts, packages/toolbar/src/toolbarPlugin.tsx
=> feat: Don't include the drop plugin

CHANGELOG.md, demo/src/App.tsx, packages/toolbar/src/index.d.ts, packages/toolbar/src/toolbarPlugin.tsx, packages/zoom/src/index.d.ts, packages/zoom/src/zoomPlugin.tsx
=> feat(zoom): Add zoom plugin options

CHANGELOG.md, demo/src/App.tsx, packages/print/src/index.d.ts, packages/print/src/printPlugin.tsx, packages/toolbar/src/index.d.ts, packages/toolbar/src/toolbarPlugin.tsx, packages/zoom/src/zoomPlugin.tsx
=> feat(print): Shortcuts option

demo/src/App.tsx, packages/attachment/src/styles/attachmentList.less, packages/attachment/src/styles/theme.less, packages/bookmark/src/styles/bookmarkItem.less, packages/bookmark/src/styles/theme.less, packages/core/src/styles/askingPassword.less, packages/core/src/styles/menuItem.less, packages/core/src/styles/theme.less, packages/default-layout/src/styles/theme.less, packages/drop/src/styles/theme.less, packages/full-screen/src/styles/theme.less, packages/print/src/styles/printProgress.less, packages/print/src/styles/theme.less, packages/thumbnail/src/styles/theme.less, packages/toolbar/src/styles/theme.less, packages/zoom/src/styles/theme.less
=> Tweak the dark theme

CHANGELOG.md, packages/search/src/useDocument.ts
=> fix(search): search plugin can cause a re-render

CHANGELOG.md, demo/src/App.tsx, packages/search/src/styles/index.less, packages/search/src/styles/searchPopover.less, packages/search/src/styles/theme.less
=> fix(search): Search results are not highlighted

CHANGELOG.md, packages/attachment/src/styles/theme.less, packages/bookmark/src/styles/theme.less, packages/core/src/styles/theme.less, packages/default-layout/src/styles/theme.less, packages/drop/src/styles/theme.less, packages/full-screen/src/styles/theme.less, packages/highlight/src/styles/theme.less, packages/print/src/styles/theme.less, packages/search/src/styles/theme.less, packages/thumbnail/src/styles/theme.less, packages/toolbar/src/styles/theme.less, packages/zoom/src/styles/theme.less
=> fix: Move CSS variables to :root

CHANGELOG.md, packages/core/src/index.d.ts, packages/core/src/portal/Modal.tsx, packages/core/src/portal/ModalBody.tsx, packages/core/src/portal/PopoverBody.tsx, packages/properties/src/ShowProperties.tsx
=> feat: Accessible Modal 

CHANGELOG.md, packages/core/src/components/Button.tsx, packages/core/src/components/Menu.tsx, packages/core/src/components/MenuDivider.tsx, packages/core/src/components/MenuItem.tsx, packages/core/src/components/MinimalButton.tsx, packages/core/src/components/PrimaryButton.tsx, packages/core/src/index.d.ts, packages/core/src/portal/Popover.tsx, packages/core/src/styles/menu.less, packages/core/src/styles/menuItem.less, packages/locale-switcher/src/LocalePopover.tsx, packages/toolbar/src/MoreActionsPopover.tsx, packages/zoom/src/ZoomPopover.tsx
=> feat: Accessible menu

CHANGELOG.md, packages/core/src/components/MenuDivider.tsx
=> feat(core): Add aria attributes for menu divider

CHANGELOG.md, packages/core/src/index.d.ts, packages/core/src/portal/Tooltip.tsx, packages/core/src/portal/TooltipBody.tsx, packages/default-layout/src/Sidebar.tsx, packages/full-screen/src/EnterFullScreenButton.tsx, packages/get-file/src/DownloadButton.tsx, packages/locale-switcher/src/LocalePopover.tsx, packages/open/src/OpenButton.tsx, packages/page-navigation/src/GoToFirstPageButton.tsx, packages/page-navigation/src/GoToLastPageButton.tsx, packages/page-navigation/src/GoToNextPageButton.tsx, packages/page-navigation/src/GoToPreviousPageButton.tsx, packages/print/src/PrintButton.tsx, packages/properties/src/ShowPropertiesButton.tsx, packages/rotate/src/RotateButton.tsx, packages/scroll-mode/src/SwitchScrollModeButton.tsx, packages/search/src/SearchPopover.tsx, packages/search/src/ShowSearchPopoverButton.tsx, packages/selection-mode/src/SwitchSelectionModeButton.tsx, packages/theme/src/SwitchThemeButton.tsx, packages/toolbar/src/MoreActionsPopover.tsx, packages/zoom/src/ZoomInButton.tsx, packages/zoom/src/ZoomOutButton.tsx
=> feat(core): Accessible Tooltip

CHANGELOG.md, packages/core/src/icons/Icon.tsx
=> feat(core): Add aria-hidden to icon

CHANGELOG.md, locales/en_US.json, packages/bookmark/src/BookmarkItem.tsx, packages/bookmark/src/BookmarkList.tsx, packages/bookmark/src/BookmarkListRoot.tsx, packages/bookmark/src/BookmarkListWithStore.tsx, packages/bookmark/src/BookmarkLoader.tsx, packages/bookmark/src/StoreProps.ts, packages/bookmark/src/bookmarkPlugin.tsx, packages/core/src/annotations/Link.tsx, packages/core/src/layouts/Inner.tsx, packages/core/src/localization/en_US.json, packages/default-layout/src/defaultLayoutPlugin.tsx, packages/thumbnail/src/ThumbnailContainer.tsx, packages/thumbnail/src/ThumbnailItem.tsx
=> feat: Add aria-label to internal links

CHANGELOG.md, demo/src/App.tsx, packages/core/src/components/MinimalButton.tsx, packages/core/src/index.d.ts, packages/print/src/Print.tsx, packages/print/src/PrintButton.tsx, packages/print/src/PrintMenuItem.tsx, packages/print/src/ShortcutHandler.tsx, packages/print/src/index.d.ts, packages/print/src/printPlugin.tsx, packages/print/src/utils/isMac.ts, packages/zoom/src/ShortcutHandler.tsx, packages/zoom/src/ZoomIn.tsx, packages/zoom/src/ZoomInButton.tsx, packages/zoom/src/ZoomOut.tsx, packages/zoom/src/ZoomOutButton.tsx, packages/zoom/src/index.d.ts, packages/zoom/src/utils/isMac.ts, packages/zoom/src/zoomPlugin.tsx
=> feat: Indicate aria attributes for shortcuts if enabled

CHANGELOG.md, packages/bookmark/src/BookmarkListRoot.tsx, packages/bookmark/src/bookmarkPlugin.tsx, packages/core/src/components/Menu.tsx, packages/core/src/components/MenuItem.tsx, packages/core/src/index.ts, packages/core/src/portal/Popover.tsx, packages/core/src/portal/Tooltip.tsx, packages/core/src/portal/TooltipBody.tsx, packages/core/src/styles/menuItem.less, packages/core/src/styles/theme.less
=> feat(core): Accessible menu

CHANGELOG.md, packages/core/src/components/Menu.tsx, packages/default-layout/src/Sidebar.tsx, packages/thumbnail/src/ThumbnailList.tsx, packages/thumbnail/src/styles/thumbnailList.less
=> feat(thumbnail): Accessible thumbnails

CHANGELOG.md, packages/search/src/Search.tsx
=> fix(search): Custom search control isn't rendered

CHANGELOG.md, demo/src/App.tsx, packages/search/src/Search.tsx, packages/search/src/SearchPopover.tsx, packages/search/src/Tracker.tsx, packages/search/src/index.d.ts, packages/search/src/searchPlugin.tsx, packages/search/src/styles/theme.less, packages/search/src/types/GetMatchSample.ts, packages/search/src/types/Match.ts, packages/search/src/types/MatchPosition.ts, packages/search/src/types/Result.ts, packages/search/src/types/StoreProps.ts, packages/search/src/useSearch.ts
=> feat(search): Expose more APIs

demo/src/App.tsx, demo/src/index.html, demo/src/index.tsx, packages/search/src/ShowSearchPopover.tsx, packages/search/src/useDocument.ts, packages/search/src/useSearch.ts
=> fix(search): Search popover isn't shown until the document is loaded

CHANGELOG.md, demo/src/App.tsx, packages/core/src/Viewer.tsx, packages/core/src/index.d.ts, packages/core/src/theme/ThemeProvider.tsx, packages/print/src/styles/theme.less
=> feat(core): Add new onSwitchTheme option

packages/bookmark/src/BookmarkListRoot.tsx
=> fix(bookmark): Link annotations aren't set aria-label attribute

CHANGELOG.md, packages/attachment/src/AttachmentList.tsx, packages/attachment/src/AttachmentLoader.tsx, packages/attachment/src/styles/attachmentList.less
=> feat(attachment): Accessible attachments

CHANGELOG.md, packages/core/src/components/Spinner.tsx, packages/core/src/index.d.ts, packages/core/src/styles/spinner.less, packages/core/src/styles/theme.less
=> feat(core): Add size for Spinner

CHANGELOG.md, packages/page-navigation/src/styles/currentPageInput.less, packages/search/src/SearchPopover.tsx
for #675 
https://user-images.githubusercontent.com/57786711/126888509-177293a8-d312-4cca-a037-482a4e969ff1.mp4
=> feat(search): Show a loading indicator while searching for a keyword

packages/core/__tests__/onSwitchTheme.test.tsx, packages/core/src/theme/ThemeProvider.tsx, packages/default-layout/src/defaultLayoutPlugin.tsx, packages/theme/__tests__/switchThemeButton.test.tsx, packages/theme/package.json, packages/toolbar/src/toolbarPlugin.tsx
=> feat(core): Add test for onSwitchTheme

packages/search/__tests__/customSearchControl.test.tsx
=> feat(search): Add test case for custom Search control

CHANGELOG.md, packages/core/src/components/Menu.tsx
=> fix(core): Automatically scroll to the top of page when opening a menu

CHANGELOG.md, packages/core/src/components/Menu.tsx
=> feat(core): Move to first/last menu item when pressing Home/End

CHANGELOG.md, packages/core/src/hooks/useClickOutside.ts
=> fix(core): Can't close the menu when using with Fluent UI

CHANGELOG.md, packages/default-layout/src/Sidebar.tsx
=> fix: activateTab() shouldn't toggle the tab

CHANGELOG.md, demo/nextjs/next-env.d.ts, packages/default-layout/src/Sidebar.tsx, packages/search/__tests__/setTargetPages.test.tsx, packages/search/src/Search.tsx, packages/search/src/Tracker.tsx, packages/search/src/index.d.ts, packages/search/src/searchPlugin.tsx, packages/search/src/types/SearchTargetPage.ts, packages/search/src/types/StoreProps.ts, packages/search/src/useSearch.ts
=> feat(search): Filter target pages

CHANGELOG.md, demo/nextjs/pages/index.tsx, packages/core/__tests__/onDocumentLoad.test.tsx, packages/core/src/Viewer.tsx, packages/core/src/index.d.ts, packages/core/src/layouts/Inner.tsx, packages/core/src/types/DocumentLoadEvent.ts, packages/core/src/types/PageChangeEvent.ts, packages/core/src/types/Plugin.ts, packages/core/src/types/ZoomEvent.ts, packages/core/src/types/index.ts
=> feat: Add file info to onDocumentLoad

CHANGELOG.md, configs/SimpleMockResizeObserver.ts, configs/setupTests.ts, demo/nextjs/pages/index.tsx, packages/core/__tests__/defaultScale.test.tsx, packages/core/src/Viewer.tsx, packages/core/src/hooks/useTrackResize.ts, packages/core/src/layouts/Inner.tsx, packages/core/src/layouts/PageSizeCalculator.tsx, packages/default-layout/src/defaultLayoutPlugin.tsx, packages/zoom/src/ZoomPopover.tsx, test-utils/mockResizeObserver.ts
=> fix(core): The pages' container overflows on initial render

CHANGELOG.md, packages/core/__tests__/defaultScale.test.tsx, packages/core/src/layouts/Inner.tsx
=> feat(core): Keep the special level when resizing the window

CHANGELOG.md, packages/core/src/components/Splitter.tsx, packages/core/src/index.d.ts, packages/core/src/index.ts, packages/core/src/styles/index.less, packages/core/src/styles/splitter.less, packages/core/src/styles/theme.less
=> feat: Add Splitter component

CHANGELOG.md, packages/default-layout/src/defaultLayoutPlugin.tsx
=> feat: The Default Layout plugin allows to resize the sidebar

CHANGELOG.md, packages/default-layout/src/defaultLayoutPlugin.tsx, packages/default-layout/src/index.d.ts, packages/toolbar/src/index.d.ts, packages/toolbar/src/toolbarPlugin.tsx
=> fix: Set plugin instances readonly

CHANGELOG.md, packages/open/src/Open.tsx, packages/open/src/OpenButton.tsx, packages/open/src/OpenMenuItem.tsx, packages/open/src/ShortcutHandler.tsx, packages/open/src/index.d.ts, packages/open/src/openPlugin.tsx, packages/open/src/types/StoreProps.ts, packages/open/src/useTriggerOpen.ts, packages/toolbar/src/index.d.ts, packages/toolbar/src/toolbarPlugin.tsx
=> feat: Support shortcuts to open a document

packages/open/src/Open.tsx, packages/open/src/OpenButton.tsx, packages/open/src/openPlugin.tsx, packages/print/src/PrintButton.tsx
=> fix: Add missing aria-keyshortcuts

CHANGELOG.md, packages/search/src/ShortcutHandler.tsx, packages/search/src/ShowSearchPopover.tsx, packages/search/src/ShowSearchPopoverButton.tsx, packages/search/src/index.d.ts, packages/search/src/searchPlugin.tsx, packages/search/src/types/StoreProps.ts
=> feat: Search shortcuts

CHANGELOG.md, packages/core/src/components/TextBox.tsx, packages/core/src/index.d.ts, packages/search/src/SearchPopover.tsx
=> feat: Automatically focus on the keyword input in the search popover

CHANGELOG.md, packages/full-screen/src/EnterFullScreen.tsx, packages/full-screen/src/EnterFullScreenButton.tsx, packages/full-screen/src/ShortcutHandler.tsx, packages/full-screen/src/fullScreenPlugin.tsx, packages/full-screen/src/index.d.ts, packages/full-screen/src/useEnterFullScreen.ts, packages/open/src/useTriggerOpen.ts
=> feat: Support shortcuts to enter the full screen mode

packages/full-screen/src/EnterFullScreenButton.tsx, packages/full-screen/src/ShortcutHandler.tsx
=> fix: Use Meta key

CHANGELOG.md, packages/thumbnail/src/ThumbnailList.tsx, packages/thumbnail/src/styles/thumbnailList.less
=> feat: Show the page numbers for thumbnails

packages/default-layout/src/Sidebar.tsx
=> fix: Remove current width after toggling the sidebar

packages/default-layout/src/Sidebar.tsx
=> feat: Remember the sidebar's width

CHANGELOG.md, packages/default-layout/src/Sidebar.tsx, packages/thumbnail/src/Cover.tsx, packages/thumbnail/src/ThumbnailList.tsx, packages/thumbnail/src/index.d.ts, packages/thumbnail/src/styles/cover.scss, packages/thumbnail/src/styles/index.scss, packages/thumbnail/src/styles/thumbnailList.scss, packages/thumbnail/src/thumbnailPlugin.tsx, packages/thumbnail/src/types/CoverProps.ts
=> feat: Add new Cover component

packages/core/src/components/Splitter.tsx, packages/default-layout/src/Sidebar.tsx, packages/default-layout/src/defaultLayoutPlugin.tsx
=> feat: Splitter supports RTL

CHANGELOG.md, packages/core/src/components/Spinner.tsx, packages/core/src/styles/spinner.scss
=> feat: Only animate Spinner when it's visible

CHANGELOG.md, packages/print/src/PrintZone.tsx
=> fix: There are extra empty pages when printing a document

packages/print/src/PrintZone.tsx
=> Remove all printing zones when printing is done

CHANGELOG.md, demo/webpack/src/App.tsx, demo/webpack/src/index.css, packages/core/src/components/Splitter.tsx
=> fix: Can't resize the sidebar when using with Fluent UI

CHANGELOG.md, configs/setupTests.ts, packages/core/src/index.d.ts, packages/core/src/types/PdfJs.ts, packages/thumbnail/src/LabelsLoader.tsx, packages/thumbnail/src/ThumbnailList.tsx
=> feat: Show the page labels if there are

CHANGELOG.md, demo/nextjs/pages/highlight-trigger-none/index.tsx, packages/highlight/src/HighlightAreaList.tsx, packages/highlight/src/highlightPlugin.tsx, packages/highlight/src/index.d.ts, packages/highlight/src/index.ts, packages/highlight/src/structs/Trigger.ts
=> feat: Add new trigger option

CHANGELOG.md, demo/nextjs/pages/index.tsx, packages/default-layout/__tests__/removeSidebar.test.tsx, packages/default-layout/src/Sidebar.tsx
=> Empty sidebar

CHANGELOG.md, demo/nextjs/pages/highlight-dynamic-areas/index.tsx, packages/highlight/src/HighlightAreaList.tsx, packages/highlight/src/HighlightState.ts, packages/highlight/src/Tracker.tsx, packages/highlight/src/highlightPlugin.tsx, packages/highlight/src/index.d.ts, packages/highlight/src/types/RenderHighlightsProps.ts, packages/highlight/src/types/StoreProps.ts
=> feat: Add new setHighlightAreas function to render areas dynamically

CHANGELOG.md, demo/nextjs/pages/highlight-dynamic-areas/index.tsx, jest-e2e.config.js, packages/core/src/components/Button.tsx, packages/core/src/index.d.ts, packages/highlight/__tests__/setHighlightAreas.e2e.ts
=> feat: Add test case for setHighlightAreas function

CHANGELOG.md, demo/nextjs/package.json, packages/core/src/layers/TextLayer.tsx
=> fix: The selected text isn't correct

CHANGELOG.md, demo/nextjs/pages/_app.tsx, demo/nextjs/pages/highlight/index.tsx, packages/highlight/src/HighlightAreaList.tsx, packages/highlight/src/highlightPlugin.tsx
=> fix: The highlight areas aren't displayed

CHANGELOG.md, demo/nextjs/pages/highlight-dynamic-areas/index.tsx, packages/highlight/src/HighlightAreaList.tsx, packages/highlight/src/HighlightState.ts, packages/highlight/src/highlightPlugin.tsx, packages/highlight/src/index.d.ts, packages/highlight/src/types/RenderHighlightsProps.ts
=> fix: Don't need setHighlightAreas anymore

CHANGELOG.md, packages/search/__tests__/keyword.test.tsx, packages/search/src/Tracker.tsx, packages/search/src/constants.ts, packages/search/src/normalizeKeyword.ts, packages/search/src/searchPlugin.tsx, packages/search/src/types/NormalizedKeyword.ts, packages/search/src/types/StoreProps.ts, packages/search/src/useSearch.ts
=> fix: Can't use special characters in the keyword

CHANGELOG.md, demo/nextjs/pages/_app.tsx, demo/nextjs/pages/index.tsx, packages/core/src/index.d.ts, packages/core/src/types/PdfJs.ts, packages/get-file/src/Download.tsx, packages/get-file/src/downloadFile.ts, packages/get-file/src/getFilePlugin.tsx, packages/get-file/src/types/StoreProps.ts
=> fix: Can't download a file with credentials

CHANGELOG.md, packages/page-navigation/src/CurrentPageLabel.tsx, packages/page-navigation/src/usePageLabels.ts
=> feat: Cache pages' labels

packages/page-navigation/src/CurrentPageLabel.tsx, packages/page-navigation/src/usePageLabels.ts
=> fix: Page labels aren't loaded in the first page

CHANGELOG.md, demo/webpack/src/App.tsx, packages/scroll-mode/src/SwitchScrollMode.tsx, packages/scroll-mode/src/Tracker.tsx, packages/scroll-mode/src/index.d.ts, packages/scroll-mode/src/scrollModePlugin.tsx, packages/scroll-mode/src/useScrollMode.ts
=> feat: Add method to switch to given scroll mode

CHANGELOG.md, packages/scroll-mode/__tests__/switchScrollMode.test.tsx, packages/toolbar/__tests__/switchScrollMode.test.tsx
=> feat: Add test case for switching scroll mode

CHANGELOG.md, demo/webpack/webpack.config.js, packages/get-file/src/Download.tsx, packages/get-file/src/downloadFile.ts
=> fix: Downloading document doesn't work on iOS Safari

CHANGELOG.md, packages/get-file/src/downloadFile.ts
=> fix: Downloading document doesn't work on iOS Chrome

packages/highlight/__tests__/setHighlightAreas.e2e.ts
=> fix: Fix e2e test for setting highlight areas

CHANGELOG.md, demo/nextjs/pages/full-screen-exit-button/index.tsx, packages/full-screen/src/ExitFullScreen.tsx, packages/full-screen/src/ExitFullScreenButton.tsx, packages/full-screen/src/fullScreenPlugin.tsx, packages/full-screen/src/index.d.ts, packages/full-screen/src/index.ts
=> feat: Customize the button to exit full screen mode

demo/nextjs/pages/full-screen-exit-button-default-layout/index.tsx, demo/nextjs/pages/full-screen-exit-button/index.tsx, jest-puppeteer.config.js, packages/full-screen/__tests__/customExitFullScreenButton.e2e.ts, packages/full-screen/__tests__/customExitFullScreenButtonDefaultLayout.e2e.ts, packages/full-screen/src/ExitFullScreen.tsx
=> feat: Add e2e test for customizing exit full screen mode

CHANGELOG.md, demo/nextjs/pages/thumbnail-render-spinner/index.tsx, demo/nextjs/styles/index.css, packages/thumbnail/src/Cover.tsx, packages/thumbnail/src/SpinnerContext.tsx, packages/thumbnail/src/ThumbnailContainer.tsx, packages/thumbnail/src/ThumbnailItem.tsx, packages/thumbnail/src/ThumbnailListWithStore.tsx, packages/thumbnail/src/index.d.ts, packages/thumbnail/src/thumbnailPlugin.tsx
=> feat: Add renderSpinner option

packages/thumbnail/src/SpinnerContext.tsx, packages/thumbnail/src/thumbnailPlugin.tsx
=> fix: Exception when renderSpinner isn't set

CHANGELOG.md, demo/nextjs/pages/thumbnail-render-thumbnail-item/index.tsx, jest.config.js, packages/thumbnail/__tests__/renderThumbnailItem.test.tsx, packages/thumbnail/src/ThumbnailList.tsx, packages/thumbnail/src/ThumbnailListWithStore.tsx, packages/thumbnail/src/index.d.ts, packages/thumbnail/src/index.ts, packages/thumbnail/src/thumbnailPlugin.tsx, packages/thumbnail/src/types/RenderThumbnailItemProps.ts, packages/thumbnail/src/types/RenderThumbnailProps.ts
=> feat: Customize thumbnail renderer

CHANGELOG.md, demo/nextjs/pages/thumbnail-render-thumbnail-item/index.tsx, demo/nextjs/pages/thumbnail-stuck-loading/index.tsx, jest-e2e.config.js, packages/thumbnail/__tests__/stuckAtLoading.e2e.ts, packages/thumbnail/src/ThumbnailListWithStore.tsx
=> fix: The thumbnails list are stuck at loading spinner

jest.config.js, packages/rotate/src/RotateButton.tsx, packages/rotate/src/RotateMenuItem.tsx, packages/scroll-mode/src/SwitchScrollModeButton.tsx, packages/scroll-mode/src/SwitchScrollModeMenuItem.tsx, packages/selection-mode/src/SwitchSelectionModeButton.tsx, packages/selection-mode/src/SwitchSelectionModeMenuItem.tsx, packages/toolbar/__tests__/testId.test.tsx
=> feat: Add test case for testId

CHANGELOG.md, packages/core/src/layers/CanvasLayer.tsx, packages/search/src/Tracker.tsx
=> Fix search order

packages/search/src/Tracker.tsx
=> fix: Compare the highlight element position properly

demo/nextjs/pages/_app.tsx, demo/nextjs/pages/full-screen-exit-button-default-layout/index.tsx, demo/nextjs/pages/full-screen-exit-button/index.tsx, demo/nextjs/pages/highlight-dynamic-areas/index.tsx, demo/nextjs/pages/highlight-trigger-none/index.tsx, demo/nextjs/pages/highlight/index.tsx, demo/nextjs/pages/search-custom-control/index.tsx, demo/nextjs/pages/search-focus-keyword/index.tsx, demo/nextjs/pages/thumbnail-render-spinner/index.tsx, demo/nextjs/pages/thumbnail-render-thumbnail-item/index.tsx, demo/nextjs/pages/thumbnail-stuck-loading/index.tsx, demo/nextjs/pages/uint8array/index.tsx, jest-e2e.config.js, packages/search/__tests__/jumpBetweenMatches.e2e.ts
=> feat: Add e2e test for navigating between matches

CHANGELOG.md, demo/nextjs/pages/thumbnail-cover/index.tsx, jest-e2e.config.js, packages/thumbnail/__tests__/cover.e2e.ts, packages/thumbnail/src/Cover.tsx, packages/thumbnail/src/styles/cover.scss
=> feat: Cover uses the image tag

CHANGELOG.md, packages/thumbnail/src/Cover.tsx, packages/thumbnail/src/styles/cover.scss
=> fix: The Cover component position isn't correct

demo/nextjs/pages/toolbar-get-file-slot/index.tsx
=> feat: Add example of customizing Download button

CHANGELOG.md, demo/nextjs/pages/full-screen-include-toolbar/index.tsx, packages/default-layout/src/defaultLayoutPlugin.tsx, packages/default-layout/src/styles/defaultLayout.scss, packages/full-screen/src/EnterFullScreen.tsx, packages/full-screen/src/ExitFullScreen.tsx, packages/full-screen/src/ExitFullScreenButtonWithTooltip.tsx, packages/full-screen/src/ShortcutHandler.tsx, packages/full-screen/src/fullScreen.ts, packages/full-screen/src/fullScreenPlugin.tsx, packages/full-screen/src/index.d.ts, packages/full-screen/src/useEnterFullScreen.ts
=> feat: Allow to customize the full screen target

CHANGELOG.md, jest-e2e.config.js, packages/full-screen/__tests__/includeToolbar.e2e.ts
=> feat: Add e2e test for including default toolbar in full screen mode

CHANGELOG.md, jest.config.js, packages/default-layout/__tests__/renderToolbarWithNumberOfPages.test.tsx, packages/page-navigation/__tests__/CurrentPageLabelDynamicDocument.test.tsx, packages/page-navigation/src/CurrentPageLabel.tsx, packages/page-navigation/src/usePageLabels.ts, packages/thumbnail/src/usePageLabels.ts, packages/toolbar/__tests__/renderToolbarWithNumberOfPages.test.tsx
=> fix: The number of pages slot isn't correct when using the renderToolbar

CHANGELOG.md, demo/nextjs/pages/thumbnail-render-thumbnail-item/index.tsx, demo/webpack/src/App.tsx, demo/webpack/src/index.tsx, packages/thumbnail/src/index.d.ts, packages/thumbnail/src/thumbnailPlugin.tsx
=> feat: Move renderThumbnailItem to Thumbnails

demo/nextjs/pages/default-layout-render-thumbnail-item/index.tsx
=> feat: Add example using renderThumbnailItem with default layout

packages/thumbnail/__tests__/renderThumbnailItem.test.tsx
=> fix: renderThumbnailItem test case

demo/nextjs/pages/thumbnail-stuck-loading/index.tsx, jest-e2e.config.js, packages/thumbnail/__tests__/stuckAtLoading.e2e.ts, packages/thumbnail/src/ThumbnailContainer.tsx, packages/thumbnail/src/ThumbnailListWithStore.tsx
=> feat: Update e2e test for thumbnail loading issue

CHANGELOG.md, packages/bookmark/src/BookmarkListRoot.tsx, packages/bookmark/src/BookmarkListWithStore.tsx, packages/bookmark/src/BookmarkLoader.tsx, packages/core/src/annotations/Link.tsx, packages/core/src/hooks/usePages.ts, packages/core/src/index.d.ts, packages/core/src/layouts/Inner.tsx, packages/core/src/types/PdfJs.ts
=> fix: The internal links don't work properly in some cases

demo/nextjs/pages/bookmark/index.tsx, demo/nextjs/pages/core/index.tsx, jest-e2e.config.js, packages/bookmark/__tests__/Bookmarks.e2e.ts, packages/bookmark/src/BookmarkItem.tsx, packages/core/__tests__/internalLinks.e2e.ts, packages/default-layout/__tests__/Bookmarks.e2e.ts
=> Test links

CHANGELOG.md, packages/core/__tests__/horizontalScrollbar.e2e.ts, packages/core/src/layouts/PageSizeCalculator.tsx, packages/default-layout/__tests__/horizontalScrollbar.e2e.ts
=> fix: No horizontal scrollbar by default

demo/nextjs/pages/thumbnail-stuck-loading/index.tsx, packages/thumbnail/__tests__/stuckAtLoading.e2e.ts, packages/thumbnail/src/ThumbnailList.tsx, packages/thumbnail/src/index.d.ts, packages/thumbnail/src/thumbnailPlugin.tsx, packages/thumbnail/src/types/RenderThumbnailItemProps.ts
=> fix: Force thumbnail list to be re-rendered when doc changes

demo/nextjs/pages/default-layout-render-thumbnail-item/index.tsx, demo/nextjs/pages/thumbnail-render-thumbnail-item/index.tsx, packages/default-layout/src/styles/sidebar.scss, packages/thumbnail/src/thumbnailPlugin.tsx
=> feat: Don't need to rerender Thumbnails

packages/core/src/layers/CanvasLayer.tsx, packages/core/src/layers/PageLayer.tsx, packages/core/src/utils/floatToRatio.ts, packages/core/src/utils/roundToDivide.ts
=> feat: Use CSS transform to scale canvas in big zoom levels

CHANGELOG.md, demo/nextjs/pages/thumbnail-cover/index.tsx, packages/core/src/utils/managePages.ts, packages/thumbnail/__tests__/cover.e2e.ts
=> fix: Cover produces same image when loading different documents

CHANGELOG.md, packages/default-layout/src/styles/defaultLayout.scss
=> fix: The sidebar doesn't fit in its container on Safari

packages/core/src/layouts/Inner.tsx
=> fix: Keep the current scroll position

packages/thumbnail/src/ThumbnailList.tsx
=> fix: Exception when switching document

CHANGELOG.md, packages/core/src/loader/DocumentLoader.tsx
=> fix: The default Spinner is used when using the renderLoader option

CHANGELOG.md, packages/full-screen/src/ExitFullScreenButton.tsx, packages/full-screen/src/styles/exitFullScreenButton.scss, packages/full-screen/src/styles/theme.scss, packages/full-screen/src/useEnterFullScreen.ts
=> fix: The exit full screen button doesn't look good in dark theme

CHANGELOG.md, packages/core/src/Viewer.tsx, packages/core/src/hooks/useScroll.ts, packages/core/src/hooks/useVirtual.ts, packages/core/src/index.d.ts, packages/core/src/index.ts, packages/core/src/layouts/Inner.tsx, packages/core/src/layouts/PageSizeCalculator.tsx, packages/core/src/structs/ScrollMode.ts
=> fix: Horizontal scroll mode

CHANGELOG.md, packages/full-screen/src/styles/fullScreenPages.scss, packages/scroll-mode/src/scrollModePlugin.tsx
=> fix: There is a black area in the full screen mode

demo/nextjs/pages/default-layout-rtl/index.tsx, demo/webpack/src/App.tsx, jest-e2e.config.js, packages/core/src/hooks/useMeasureRect.ts, packages/core/src/hooks/useScroll.ts, packages/core/src/hooks/useVirtual.ts, packages/core/src/index.d.ts, packages/core/src/layouts/Inner.tsx, packages/core/src/types/Rect.ts, packages/default-layout/__tests__/scrollMode.e2e.ts, packages/default-layout/__tests__/scrollModeRtl.e2e.ts, packages/scroll-mode/src/SwitchScrollModeButton.tsx, packages/scroll-mode/src/SwitchScrollModeDecorator.tsx, packages/scroll-mode/src/SwitchScrollModeMenuItem.tsx, packages/toolbar/src/MoreActionsPopover.tsx
=> Wrapped scroll mode

CHANGELOG.md, demo/nextjs/pages/core-initial-page/index.tsx, demo/nextjs/pages/core-onpagechange/index.tsx, demo/nextjs/pages/default-layout-initial-page/index.tsx, demo/nextjs/pages/default-layout-onpagechange/index.tsx, packages/core/__tests__/initialPage.e2e.ts, packages/core/__tests__/onPageChange.e2e.ts, packages/core/__tests__/onPageChange.test.tsx, packages/core/src/Viewer.tsx, packages/core/src/layouts/Inner.tsx, packages/default-layout/__tests__/initialPage.e2e.ts, packages/default-layout/__tests__/onPageChange.e2e.ts
=> fix: onPageChange event fires more than once

CHANGELOG.md, demo/nextjs/pages/thumbnail-render-thumbnail-item-dynamic-document/index.tsx, demo/webpack/src/index.html, jest-e2e.config.js, packages/thumbnail/__tests__/renderThumbnailItem.test.tsx, packages/thumbnail/__tests__/renderThumbnailItemDynamicDocument.e2e.ts, packages/thumbnail/src/ThumbnailContainer.tsx, packages/thumbnail/src/thumbnailPlugin.tsx
=> fix: renderThumbnailItem doesn't work with dynamic document

packages/thumbnail/src/Cover.tsx, packages/thumbnail/src/CoverInner.tsx
=> fix: Cover isn't rendered

packages/thumbnail/__tests__/Cover.test.tsx, packages/thumbnail/src/CoverInner.tsx
=> More Cover test cases

packages/core/src/hooks/useScroll.ts, packages/core/src/hooks/useVirtual.ts, packages/core/src/layouts/Inner.tsx, packages/default-layout/__tests__/BookmarksScrollMode.e2e.ts
=> fix: Can't jump to destination from Bookmark when switching scroll mode

CHANGELOG.md, packages/core/src/layouts/Inner.tsx, packages/default-layout/__tests__/scrollMode.e2e.ts
=> fix: Keep the current page after switching the scroll mode

CHANGELOG.md, demo/nextjs/pages/core-render-page/index.tsx, packages/core/__tests__/renderPage.e2e.ts, packages/core/src/index.d.ts, packages/core/src/layers/CanvasLayer.tsx, packages/core/src/layers/PageLayer.tsx, packages/core/src/layouts/Inner.tsx, packages/core/src/services/renderQueueService.ts, packages/core/src/types/RenderPage.ts, packages/thumbnail/src/ThumbnailList.tsx
=> fix: renderPage

packages/core/src/layers/PageLayer.tsx, packages/default-layout/src/defaultLayoutPlugin.tsx, packages/search/src/Tracker.tsx, packages/search/src/searchPlugin.tsx, packages/toolbar/src/toolbarPlugin.tsx
=> feat(search-plugin): Track only pages which are in the current range

CHANGELOG.md, configs/setupTests.ts, demo/nextjs/pages/thumbnail-stuck-loading/index.tsx, packages/core/__tests__/onPageChange.test.tsx, packages/core/src/components/LazyRender.tsx, packages/core/src/components/Spinner.tsx, packages/core/src/hooks/useRafState.ts, packages/core/src/index.d.ts, packages/core/src/layers/PageLayer.tsx, packages/default-layout/__tests__/BookmarksScrollModeRtl.e2e.ts, packages/default-layout/__tests__/Thumbnails.test.tsx, packages/page-navigation/__tests__/CurrentPageLabelDynamicDocument.test.tsx, packages/thumbnail/__tests__/Thumbnails.test.tsx, packages/thumbnail/__tests__/ThumbnailsDynamicDocument.test.tsx, packages/thumbnail/__tests__/pageLabel.test.tsx, packages/thumbnail/__tests__/renderCustomPageLabel.test.tsx, packages/thumbnail/__tests__/renderSpinner.test.tsx, packages/thumbnail/__tests__/renderThumbnailItem.test.tsx, packages/thumbnail/__tests__/rtl.test.tsx, packages/thumbnail/__tests__/stuckAtLoading.e2e.ts, packages/thumbnail/__tests__/switchDocument.test.tsx, packages/thumbnail/src/ThumbnailList.tsx, packages/thumbnail/src/ThumbnailListWithStore.tsx, packages/thumbnail/src/styles/thumbnailList.scss, packages/thumbnail/src/styles/thumbnailListLoader.scss, packages/toolbar/__tests__/renderToolbarWithNumberOfPages.test.tsx
=> More tests

packages/core/src/hooks/useVirtual.ts
=> fix: Don't use ResizeObserver

CHANGELOG.md, demo/webpack/src/index.html, packages/core/src/layers/CanvasLayer.tsx
=> fix: The pages are blank initially

CHANGELOG.md, packages/toolbar/src/index.d.ts
=> fix: The ScrollModePluginProps type isn't defined

CHANGELOG.md, packages/search/__tests__/keepCurrentHighlightAfterZoom.test.tsx, packages/search/src/Search.tsx, packages/search/src/Tracker.tsx, packages/search/src/searchPlugin.tsx, packages/search/src/types/StoreProps.ts
=> Fix current highlight

CHANGELOG.md, demo/nextjs/pages/search-sidebar/index.tsx, packages/search/__tests__/jumpToMatch.e2e.ts
=> Fix jumpToMatch

CHANGELOG.md, demo/nextjs/pages/search-custom-control/index.tsx, packages/search/__tests__/clearKeyword.e2e.ts, packages/search/src/useSearch.ts
=> fix: clearHighlights and clearKeyword should remove all highlights

CHANGELOG.md, packages/core/src/hooks/useVirtual.ts, packages/default-layout/__tests__/CurrentPageLabel.test.tsx, packages/search/src/Tracker.tsx
=> fix: Don't highlight spaces between words

CHANGELOG.md, packages/full-screen/src/fullScreen.ts
=> fix: Typo in full screen change event

CHANGELOG.md, packages/search/src/ShortcutHandler.tsx
=> feat: Open search popover when the mouse is inside the viewer container

CHANGELOG.md, packages/core/src/index.d.ts, packages/core/src/portal/Popover.tsx, packages/search/src/ShowSearchPopover.tsx
=> feat: It's able to scroll the pages when opening the search popover

CHANGELOG.md, packages/thumbnail/__tests__/rotateDocument.e2e.ts, packages/thumbnail/src/thumbnailPlugin.tsx
=> fix: The thumbnails aren't rotated after rotating the document

CHANGELOG.md, packages/core/src/Viewer.tsx, packages/core/src/index.d.ts, packages/core/src/layouts/Inner.tsx, packages/core/src/types/RotateEvent.ts, packages/core/src/types/index.ts
=> feat: Add onRotate callback

CHANGELOG.md, packages/core/src/Viewer.tsx, packages/core/src/index.d.ts, packages/core/src/layouts/Inner.tsx, packages/core/src/types/RotatePageEvent.ts, packages/core/src/types/index.ts
=> feat: Add onRotatePage event

CHANGELOG.md, demo/nextjs/pages/rotate-page/index.tsx, packages/rotate/src/RotatePage.tsx, packages/rotate/src/index.d.ts, packages/rotate/src/index.ts, packages/rotate/src/rotatePlugin.tsx, packages/rotate/src/types/RenderRotatePageProps.ts
=> feat: Add RotatePage component

demo/nextjs/pages/default-layout-rotate-page/index.tsx, demo/nextjs/pages/thumbnail-rotate-page/index.tsx
=> Rotate example

demo/nextjs/pages/core-rotate-page-with-thumbnails/index.tsx, demo/nextjs/pages/default-layout-rotate-page/index.tsx, demo/nextjs/pages/thumbnail-rotate-page/index.tsx, packages/core/src/index.d.ts, packages/core/src/layouts/Inner.tsx, packages/core/src/types/ViewerState.ts, packages/thumbnail/src/ThumbnailList.tsx, packages/thumbnail/src/ThumbnailListWithStore.tsx, packages/thumbnail/src/thumbnailPlugin.tsx, packages/thumbnail/src/types/StoreProps.ts
=> Rotate single page examples

demo/nextjs/pages/rotate-page-with-thumbnails/index.tsx
=> feat: Add new example of using RotatePage and thumbnails

demo/nextjs/pages/core-rotate-page-with-thumbnails/index.tsx, demo/nextjs/pages/core-rotate-page/index.tsx, demo/nextjs/pages/default-layout-rotate-page/index.tsx, demo/nextjs/pages/rotate-page-with-thumbnails/index.tsx, demo/nextjs/pages/rotate-page/index.tsx, demo/nextjs/pages/thumbnail-rotate-page/index.tsx, jest-e2e.config.js, packages/core/__tests__/rotatePage.e2e.ts, packages/core/__tests__/rotatePageWithThumbnails.e2e.ts, packages/default-layout/__tests__/rotatePage.e2e.ts, packages/rotate/__tests__/rotatePage.e2e.ts, packages/rotate/__tests__/rotatePageWithThumbnails.e2e.ts, packages/thumbnail/__tests__/rotatePage.e2e.ts
=> Rotate page tests

jest.config.js, packages/core/__tests__/rotatePage.test.tsx, packages/default-layout/__tests__/rotatePage.test.tsx, packages/rotate/__tests__/rotatePage.test.tsx, packages/thumbnail/__tests__/rotatePage.test.tsx, packages/thumbnail/__tests__/rotatePageWithThumbnails.test.tsx, test-utils/mockResizeObserver.ts
=> More unit tests for rotating single page

packages/core/__tests__/initialPage.e2e.ts, packages/core/__tests__/internalLinks.e2e.ts, packages/default-layout/__tests__/Bookmarks.e2e.ts, packages/default-layout/__tests__/BookmarksScrollMode.e2e.ts, packages/default-layout/__tests__/BookmarksScrollModeRtl.e2e.ts, packages/default-layout/__tests__/differentDimensions.e2e.ts, packages/default-layout/__tests__/differentDimensionsHorizontalMode.e2e.ts, packages/default-layout/__tests__/differentDimensionsWrappedMode.e2e.ts, packages/default-layout/__tests__/initialPage.e2e.ts, packages/default-layout/__tests__/scrollMode.e2e.ts, packages/default-layout/__tests__/scrollModeRtl.e2e.ts
=> Fix e2e tests

CHANGELOG.md, demo/nextjs/pages/bookmark-is-expanded/index.tsx, packages/bookmark/src/BookmarkItem.tsx, packages/bookmark/src/BookmarkList.tsx, packages/bookmark/src/BookmarkListRoot.tsx, packages/bookmark/src/BookmarkListWithStore.tsx, packages/bookmark/src/BookmarkLoader.tsx, packages/bookmark/src/bookmarkPlugin.tsx, packages/bookmark/src/index.d.ts, packages/bookmark/src/index.ts, packages/bookmark/src/types/IsBookmarkExpanded.ts
=> feat: Set bookmarks expanded or collapsed initially

CHANGELOG.md, packages/bookmark/__tests__/CollapsedBookmarksDynamicDocument.e2e.ts, packages/bookmark/__tests__/isBookmarkExpanded.e2e.ts, packages/bookmark/__tests__/isBookmarkExpanded.test.tsx, packages/bookmark/src/BookmarkItem.tsx
=> Bookmark expanded tests

CHANGELOG.md, packages/bookmark/src/BookmarkItem.tsx, packages/bookmark/src/styles/bookmarkItem.scss
=> feat: Align bookmark titles

CHANGELOG.md, packages/core/src/layouts/PageSizeCalculator.tsx, packages/page-navigation/src/CurrentPageLabel.tsx, packages/page-navigation/src/NumberOfPages.tsx, packages/page-navigation/src/index.d.ts, packages/page-navigation/src/index.ts, packages/page-navigation/src/pageNavigationPlugin.tsx, packages/page-navigation/src/types/GoToPage.ts, packages/page-navigation/src/types/index.ts, packages/toolbar/src/index.d.ts, packages/toolbar/src/toolbarPlugin.tsx, packages/toolbar/src/types/ToolbarSlot.ts
=> Number of pages

CHANGELOG.md, demo/nextjs/pages/search-custom-control/index.tsx, packages/search/__tests__/wholeWords.e2e.ts, packages/search/__tests__/wholeWords.test.tsx, packages/search/src/Tracker.tsx, packages/search/src/constants.ts, packages/search/src/normalizeKeyword.ts, packages/search/src/types/NormalizedKeyword.ts
=> fix: The hightlights are lost when the whole words option is enabled

CHANGELOG.md, packages/core/src/index.d.ts, packages/core/src/index.ts, packages/core/src/layouts/Inner.tsx, packages/core/src/services/renderQueueService.ts, packages/thumbnail/src/FetchLabels.tsx, packages/thumbnail/src/ThumbnailList.tsx
=> fix: Support React 18 Strict mode

CHANGELOG.md, demo/nextjs/pages/thumbnail-render-thumbnail-item-dynamic-document/index.tsx, demo/nextjs/pages/thumbnail-render-thumbnail-item/index.tsx, demo/nextjs/pages/thumbnail-width/index.tsx, packages/thumbnail/__tests__/ThumbnailsDynamicDocument.test.tsx, packages/thumbnail/__tests__/renderThumbnailItem.e2e.ts, packages/thumbnail/__tests__/renderThumbnailItem.test.tsx, packages/thumbnail/__tests__/renderThumbnailItemDynamicDocument.e2e.ts, packages/thumbnail/__tests__/thumbnailWidth.e2e.ts, packages/thumbnail/__tests__/thumbnailWidth.test.tsx, packages/thumbnail/src/ThumbnailContainer.tsx, packages/thumbnail/src/ThumbnailList.tsx, packages/thumbnail/src/ThumbnailListWithStore.tsx, packages/thumbnail/src/index.d.ts, packages/thumbnail/src/thumbnailPlugin.tsx
=> feat: Add new option to customize width of thumbnails

demo/nextjs/pages/default-layout-strict-mode/index.tsx, packages/core/__tests__/strictMode.test.tsx, packages/default-layout/__tests__/strictMode.e2e.ts, packages/thumbnail/__tests__/strictMode.test.tsx
=> Strict mode tests

CHANGELOG.md, packages/core/src/layers/CanvasLayer.tsx
=> fix: The pages are flickering when zooming the document

CHANGELOG.md, packages/core/src/index.d.ts, packages/core/src/services/renderQueueService.ts, packages/thumbnail/src/ThumbnailList.tsx
=> fix: There is a page that is not rendered even it is visible

CHANGELOG.md, demo/nextjs/pages/core-initial-page/index.tsx, packages/core/src/layouts/Inner.tsx
=> fix: The initialPage option doesn't work

CHANGELOG.md, configs/setupTests.ts, packages/search/__tests__/enterToJumpToNextMatch.e2e.ts, packages/search/__tests__/enterToJumpToNextMatch.test.tsx, packages/search/src/SearchPopover.tsx, packages/search/src/useSearch.ts
=> feat: Clicking Enter jumps to the next match

CHANGELOG.md, demo/nextjs/pages/default-layout-initial-page/index.tsx, packages/default-layout/__tests__/initialPage.e2e.ts, packages/thumbnail/src/ThumbnailList.tsx, packages/thumbnail/src/ThumbnailListWithStore.tsx
=> fix: Automatically scroll to the thumbnail of the initial page

CHANGELOG.md, demo/nextjs/pages/default-layout-render-loader/index.tsx, demo/nextjs/pages/highlight-dynamic-areas/index.tsx, packages/core/__tests__/renderLoader.test.tsx, packages/core/src/loader/DocumentLoader.tsx, packages/highlight/__tests__/setHighlightAreas.e2e.ts
=> feat: Support documents which are optimized for web

CHANGELOG.md, packages/core/src/layers/PageLayer.tsx
=> fix: The text might not be selectable if a plugin registers renderPageLayer

CHANGELOG.md, packages/core/__tests__/internalLinks.e2e.ts, packages/core/__tests__/onPageChange.e2e.ts, packages/core/src/hooks/useScroll.ts, packages/core/src/hooks/useVirtual.ts, packages/core/src/layouts/Inner.tsx, packages/core/src/utils/easeOutQuart.ts, packages/core/src/utils/smoothScroll.ts
=> Smooth scroll

CHANGELOG.md, packages/core/src/index.d.ts, packages/core/src/index.ts, packages/core/src/structs/PageMode.ts, packages/core/src/types/PdfJs.ts, packages/default-layout/src/defaultLayoutPlugin.tsx, packages/default-layout/src/index.d.ts, packages/default-layout/src/index.ts, packages/default-layout/src/setInitialTabFromPageMode.ts
=> feat: Set initial tab from page mode

CHANGELOG.md, demo/nextjs/pages/default-layout-initial-tab-page-mode/index.tsx, demo/nextjs/pages/default-layout-initial-tab/index.tsx, packages/default-layout/__tests__/setInitialTab.e2e.ts, packages/default-layout/__tests__/setInitialTab.test.tsx, packages/default-layout/__tests__/setInitialTabFromPageMode.e2e.ts, packages/default-layout/__tests__/setInitialTabFromPageMode.test.tsx
=> Initial tab tests

demo/nextjs/pages/5000-of-dummy/index.tsx, packages/default-layout/src/defaultLayoutPlugin.tsx
=> fix: Check if setInitialTab is set

CHANGELOG.md, demo/nextjs/pages/highlight/index.tsx, packages/core/src/layers/PageLayer.tsx
=> fix: Can't add highlight to selected text

CHANGELOG.md, packages/page-navigation/__tests__/shortcuts.e2e.ts, packages/page-navigation/src/ShortcutHandler.tsx, packages/page-navigation/src/index.d.ts, packages/page-navigation/src/pageNavigationPlugin.tsx
=> Page navigation shortcuts

packages/search/__tests__/renderHighlight.test.tsx
=> feat(test): Customize highlight elements

CHANGELOG.md, packages/default-layout/__tests__/setInitialTab.test.tsx, packages/default-layout/src/Sidebar.tsx
=> fix: Make sure the target tab index to be valid

CHANGELOG.md, packages/highlight/src/Tracker.tsx
=> feat: Support double click to select entire text

CHANGELOG.md, packages/core/src/layers/TextLayer.tsx, packages/highlight/src/highlightPlugin.tsx, packages/search/__tests__/keywordWithHighlightPlugin.test.tsx, packages/search/src/Highlights.tsx
=> fix: Can't use initial keyword when using with highlight plugin

packages/search/src/Highlights.tsx
=> fix: Scroll to current match when all matches are highlighted

CHANGELOG.md, configs/setupTests.ts, demo/nextjs/pages/print/index.tsx, packages/print/__tests__/print.test.tsx, packages/print/src/PageThumbnail.tsx, packages/print/src/PageThumbnailContainer.tsx, packages/print/src/PrintZone.tsx, packages/print/src/index.d.ts, packages/print/src/isRunningInJest.ts, packages/print/src/printPlugin.tsx
=> feat: Expose print function

CHANGELOG.md, packages/print/src/PrintContainer.tsx, packages/print/src/PrintZone.tsx, packages/print/src/index.d.ts, packages/print/src/printPlugin.tsx
=> feat: Allow to choose pages when printing a document

CHANGELOG.md, demo/nextjs/pages/print-progress/index.tsx, packages/print/__tests__/print.test.tsx, packages/print/__tests__/renderProgressBar.test.tsx, packages/print/src/PrintContainer.tsx, packages/print/src/index.d.ts, packages/print/src/isRunningInJest.ts, packages/print/src/printPlugin.tsx
=> feat: customize the progress bar

CHANGELOG.md, demo/nextjs/pages/print-pages/index.tsx, packages/print/__tests__/setPages.test.tsx, packages/print/__tests__/setPagesFunction.test.tsx, packages/print/src/PageThumbnail.tsx, packages/print/src/PageThumbnailContainer.tsx, packages/print/src/PrintContainer.tsx, packages/print/src/PrintZone.tsx, packages/print/src/getAllPagesNumbers.ts, packages/print/src/getCustomPagesNumbers.ts, packages/print/src/getEvenPagesNumbers.ts, packages/print/src/getOddPagesNumbers.ts, packages/print/src/index.d.ts, packages/print/src/index.ts, packages/print/src/printPlugin.tsx
=> feat: Define custom pages numbers

CHANGELOG.md, packages/toolbar/src/index.d.ts, packages/toolbar/src/toolbarPlugin.tsx
=> fix: Page navigation plugin options are missing

CHANGELOG.md, packages/search/src/ShortcutHandler.tsx
=> fix: The search popover always shows up after pressing shortcuts

CHANGELOG.md, packages/page-navigation/src/ShortcutHandler.tsx
=> fix: The viewer always navigates to previous, next pages

CHANGELOG.md, packages/core/src/annotations/AnnotationLayerBody.tsx, packages/page-navigation/src/ShortcutHandler.tsx, packages/page-navigation/src/pageNavigationPlugin.tsx, packages/page-navigation/src/types/StoreProps.ts, packages/toolbar/src/toolbarPlugin.tsx
=> feat: Bring users to the previous clicked link annotation

CHANGELOG.md, packages/page-navigation/__tests__/jumpBackPreviousAnnotation.e2e.ts
=> feat(e2e): Jump back to the previous clicked link annotation

CHANGELOG.md, packages/core/src/Viewer.tsx, packages/core/src/loader/DocumentLoader.tsx, packages/core/src/types/CharacterMap.ts, packages/core/src/types/index.ts
=> fix: CharacterMap type isn't exported

demo/nextjs/pages/default-layout-render-bookmark-item/index.tsx
=> feat: Customize bookmark items with default layout

CHANGELOG.md, packages/default-layout/__tests__/toggleTab.test.tsx, packages/default-layout/src/Sidebar.tsx, packages/default-layout/src/defaultLayoutPlugin.tsx, packages/default-layout/src/index.d.ts, packages/default-layout/src/types/StoreProps.ts
=> feat: Add toggleTab function

demo/nextjs/pages/default-layout-click-bookmark/index.tsx, packages/default-layout/src/Sidebar.tsx
=> feat: Toggle bookmark tab when clicking a bookmark item

CHANGELOG.md, packages/core/__tests__/onPageChangeWithInitialPage.e2e.ts, packages/core/src/layouts/Inner.tsx
=> fix: onPageChange doesn't trigger properly

CHANGELOG.md, packages/core/src/annotations/Link.tsx, packages/core/src/utils/sanitizeUrl.ts
=> fix: Sanitize annotation link URL

CHANGELOG.md, packages/bookmark/src/BookmarkListRoot.tsx, packages/core/src/annotations/Link.tsx, packages/page-navigation/__tests__/jumpBackPreviousAnnotation.e2e.ts, packages/page-navigation/src/pageNavigationPlugin.tsx
=> fix: Can't render certain PDF documents

CHANGELOG.md, demo/nextjs/pages/core-initial-rotation/index.tsx, packages/core/__tests__/initialRotation.e2e.ts, packages/core/__tests__/initialRotation.test.tsx, packages/core/src/Viewer.tsx, packages/core/src/index.d.ts, packages/core/src/layouts/Inner.tsx
=> feat: Add initial rotation

CHANGELOG.md, packages/core/src/index.d.ts, packages/core/src/layers/PageLayer.tsx, packages/core/src/store/createStore.ts, packages/core/src/types/Plugin.ts, packages/core/src/types/Store.ts, packages/highlight/src/Tracker.tsx, packages/highlight/src/getTextFromOffsets.ts
=> Selection index

CHANGELOG.md, demo/nextjs/pages/thumbnail-cover-rotated/index.tsx, packages/thumbnail/__tests__/coverRotatedPage.e2e.ts, packages/thumbnail/__tests__/coverRotatedPage.test.tsx, packages/thumbnail/src/Cover.tsx, packages/thumbnail/src/CoverInner.tsx
=> fix: Cover component doesn't rotate the corresponding rotated page

demo/nextjs/pages/rotate-cover/index.tsx, packages/thumbnail/__tests__/Cover.test.tsx, packages/thumbnail/__tests__/coverRotatedPage.test.tsx, packages/thumbnail/__tests__/rotateCover.e2e.ts, packages/thumbnail/__tests__/rotateCover.test.tsx, packages/thumbnail/src/CoverInner.tsx, packages/thumbnail/src/styles/cover.scss
=> fix: Rotate a cover when rotating the associate page

CHANGELOG.md, packages/highlight/src/Tracker.tsx, packages/highlight/src/index.d.ts, packages/highlight/src/types/SelectionData.ts
=> feat: Add selected text to SelectionData

CHANGELOG.md, packages/highlight/src/Tracker.tsx, packages/highlight/src/getTextFromOffsets.ts, packages/highlight/src/index.d.ts, packages/highlight/src/types/DivText.ts, packages/highlight/src/types/SelectionData.ts
=> feat: Add list of div texts

CHANGELOG.md, packages/core/src/hooks/useClickOutside.ts
=> fix: Popover doesn't work inside ShadowDOM

CHANGELOG.md, demo/nextjs/pages/highlight-switch-trigger/index.tsx, packages/highlight/src/Tracker.tsx, packages/highlight/src/highlightPlugin.tsx, packages/highlight/src/index.d.ts, packages/highlight/src/types/StoreProps.ts
=> feat: Add function to switch trigger mode

CHANGELOG.md, packages/bookmark/__tests__/rememberExpandedState.e2e.ts, packages/bookmark/__tests__/rememberExpandedState.test.tsx, packages/bookmark/src/BookmarkItem.tsx, packages/bookmark/src/BookmarkList.tsx, packages/bookmark/src/BookmarkListRoot.tsx, packages/bookmark/src/bookmarkPlugin.tsx, packages/bookmark/src/index.d.ts, packages/bookmark/src/types/RenderBookmarkItemProps.ts, packages/bookmark/src/types/StoreProps.ts, packages/highlight/src/ClickDrag.tsx, packages/highlight/src/highlightPlugin.tsx
=> feat: Keep the expanded/collapsed state of each bookmark

CHANGELOG.md, packages/open/src/OpenButton.tsx, packages/open/src/OpenMenuItem.tsx, packages/search/__tests__/keepHighlightAfterZoomToolbar.e2e.ts
=> feat: The open file dialog filters PDF files by default

CHANGELOG.md, packages/search/src/styles/searchPopover.scss
=> feat: Adjust pointer when hovering over checkboxes inside search popover

CHANGELOG.md, packages/core/src/annotations/Caret.tsx, packages/core/src/annotations/Circle.tsx, packages/core/src/annotations/FileAttachment.tsx, packages/core/src/annotations/FreeText.tsx, packages/core/src/annotations/Highlight.tsx, packages/core/src/annotations/Ink.tsx, packages/core/src/annotations/Line.tsx, packages/core/src/annotations/Polygon.tsx, packages/core/src/annotations/Polyline.tsx, packages/core/src/annotations/Popup.tsx, packages/core/src/annotations/PopupWrapper.tsx, packages/core/src/annotations/Square.tsx, packages/core/src/annotations/Squiggly.tsx, packages/core/src/annotations/Stamp.tsx, packages/core/src/annotations/StrikeOut.tsx, packages/core/src/annotations/Text.tsx, packages/core/src/annotations/Underline.tsx, packages/core/src/annotations/getContents.ts, packages/core/src/annotations/getTitle.ts, packages/core/src/index.d.ts, packages/core/src/types/PdfJs.ts
=> fix: Replace the deprecated contents and title properties

CHANGELOG.md, demo/nextjs/pages/highlight-switch-trigger/index.tsx, demo/nextjs/pages/highlight/index.tsx, packages/core/src/layouts/Inner.tsx, packages/highlight/__tests__/jumpToHighlightArea.e2e.ts
=> fix: jumpToHighlightArea does not work properly with some documents

CHANGELOG.md, packages/bookmark/src/BookmarkListRoot.tsx, packages/bookmark/src/bookmarkPlugin.tsx, packages/bookmark/src/types/StoreProps.ts, packages/core/__tests__/linkAnnotationTitle.e2e.ts, packages/core/__tests__/linkAnnotationTitle.test.tsx, packages/core/src/annotations/AnnotationLayer.tsx, packages/core/src/annotations/AnnotationLayerBody.tsx, packages/core/src/annotations/Link.tsx, packages/core/src/layers/PageLayer.tsx, packages/core/src/layouts/Inner.tsx, packages/core/src/layouts/useOutlines.ts
=> feat: Set title and aria-label attributes for link annotations

packages/bookmark/__tests__/rememberExpandedState.test.tsx
=> fix(test): Remember expanded/collapsed state of each bookmark

CHANGELOG.md, packages/core/src/index.d.ts, packages/core/src/layouts/Inner.tsx, packages/core/src/types/RenderViewer.ts, packages/print/src/PageThumbnailContainer.tsx, packages/print/src/PrintContainer.tsx, packages/print/src/PrintZone.tsx, packages/print/src/printPlugin.tsx
=> feat: Pass pageSizes to renderViewer

CHANGELOG.md, demo/nextjs/pages/core-initial-page-different-dimensions/index.tsx, packages/core/__tests__/initialPage.e2e.ts
=> feat(e2e): initialPage with different dimensions document

CHANGELOG.md, demo/nextjs/pages/rotate-buttons/index.tsx, packages/core/src/layouts/Inner.tsx, packages/default-layout/__tests__/rotate.e2e.ts, packages/rotate/__tests__/rotateButtons.e2e.ts
=> fix: Keep the current page after rotating the document

packages/core/__tests__/pageMargin.test.tsx, packages/default-layout/__tests__/pageMargin.e2e.ts, packages/default-layout/__tests__/pageMargin.test.tsx
=> Page margin test cases

packages/core/src/layouts/Inner.tsx
=> fix: Jump to given destination

demo/webpack/src/App.tsx, packages/core/src/Viewer.tsx, packages/core/src/hooks/useVirtual.ts, packages/core/src/index.d.ts, packages/core/src/index.ts, packages/core/src/layers/PageLayer.tsx, packages/core/src/layouts/Inner.tsx, packages/core/src/structs/SpreadsMode.ts, packages/core/src/styles/inner.scss, packages/core/src/styles/pageLayer.scss
=> feat: Odd spreads mode

packages/core/src/hooks/useScroll.ts, packages/core/src/hooks/useVirtual.ts, packages/core/src/structs/ScrollDirection.ts, packages/core/src/utils/smoothScroll.ts
=> feat: Scroll to given destination in Odd Spreads mode

CHANGELOG.md, locales/en_US.json, packages/core/src/hooks/useVirtual.ts, packages/core/src/index.d.ts, packages/core/src/layouts/Inner.tsx, packages/core/src/structs/ScrollMode.ts, packages/core/src/styles/inner.scss, packages/scroll-mode/src/PageScrollingIcon.tsx, packages/scroll-mode/src/SwitchScrollModeButton.tsx, packages/scroll-mode/src/SwitchScrollModeDecorator.tsx, packages/scroll-mode/src/SwitchScrollModeMenuItem.tsx, packages/scroll-mode/src/index.d.ts, packages/scroll-mode/src/index.ts, packages/toolbar/src/MoreActionsPopover.tsx
=> feat: New single page scrolling mode

CHANGELOG.md, packages/core/src/layouts/Inner.tsx, packages/default-layout/__tests__/keepScrollPositionAfterZooming.e2e.ts, packages/default-layout/__tests__/keepScrollPositionAfterZoomingBigDocument.e2e.ts
=> fix: Zooming doesn't keep current position properly

demo/webpack/src/App.tsx, packages/core/src/hooks/useVirtual.ts, packages/core/src/layouts/Inner.tsx, packages/core/src/utils/chunk.ts
=> fix: Determine the range of pages in OddSpreads mode

demo/webpack/src/App.tsx, packages/core/src/hooks/useVirtual.ts, packages/core/src/layouts/Inner.tsx, packages/core/src/styles/inner.scss
=> feat: Add even spreads mode

packages/core/src/layouts/Inner.tsx, packages/core/src/styles/inner.scss
=> feat: Center the page content in the page scrolling mode

packages/core/src/hooks/useVirtual.ts, packages/core/src/layouts/Inner.tsx
=> feat: The first and the last items are treated as covers

packages/core/src/Viewer.tsx, packages/core/src/layouts/Inner.tsx, packages/core/src/layouts/PageSizeCalculator.tsx, packages/core/src/layouts/calculateScale.ts
=> fix: Calculate scale for special zoom levels

CHANGELOG.md, demo/webpack/src/App.tsx, packages/core/src/Viewer.tsx, packages/core/src/hooks/useVirtual.ts, packages/core/src/index.d.ts, packages/core/src/index.ts, packages/core/src/layers/PageLayer.tsx, packages/core/src/layouts/Inner.tsx, packages/core/src/layouts/PageSizeCalculator.tsx, packages/core/src/layouts/calculateScale.ts, packages/core/src/structs/ViewMode.ts
=> refactor: Change SpreadsMode to ViewMode

packages/core/src/hooks/useVirtual.ts, packages/core/src/layers/PageLayer.tsx, packages/core/src/layouts/Inner.tsx, packages/core/src/styles/inner.scss, packages/core/src/styles/pageLayer.scss
=> feat: Re-render pages after switching viewmode

packages/scroll-mode/src/SwitchScrollMode.tsx, packages/scroll-mode/src/SwitchScrollModeButton.tsx, packages/scroll-mode/src/SwitchScrollModeMenuItem.tsx, packages/scroll-mode/src/SwitchViewMode.tsx, packages/scroll-mode/src/SwitchViewModeButton.tsx, packages/scroll-mode/src/SwitchViewModeMenuItem.tsx, packages/scroll-mode/src/index.d.ts, packages/scroll-mode/src/scrollModePlugin.tsx, packages/scroll-mode/src/switchScrollMode.ts, packages/scroll-mode/src/switchViewMode.ts, packages/scroll-mode/src/types/RenderSwitchScrollModeProps.ts, packages/scroll-mode/src/types/RenderSwitchViewModeProps.ts
=> feat: The horizontal/wrapped scrolling mode only accepts single page viewmode

packages/core/src/hooks/useScroll.ts, packages/core/src/utils/smoothScroll.ts
=> fix: Navigate between pages in the horizontal scroll mode

packages/core/src/virtualizer/buildItemStyles.ts, packages/core/src/virtualizer/calculateRange.ts, packages/core/src/virtualizer/useVirtual.ts
=> fix: Support RTL for dual page viewmode

demo/nextjs/pages/default-layout-page-margin/index.tsx, packages/core/src/index.d.ts, packages/core/src/layouts/Inner.tsx, packages/core/src/types/PageLayout.ts
=> feat: Add viewmode and scroll mode to PageLayout's buildPageStyles

demo/nextjs/pages/default-layout-different-dimensions/index.tsx, packages/default-layout/__tests__/differentDimensions.e2e.ts, packages/default-layout/__tests__/differentDimensionsHorizontalMode.e2e.ts, packages/default-layout/__tests__/differentDimensionsPageScrollMode.e2e.ts, packages/default-layout/__tests__/differentDimensionsWrappedMode.e2e.ts
=> feat(e2e): Document with different page dimensions (page scroll mode)

packages/core/src/styles/inner.scss, packages/default-layout/__tests__/dualPageCoverViewModeDifferentDimensions.e2e.ts, packages/default-layout/__tests__/dualPageCoverViewModeDifferentDimensionsAnnotation.e2e.ts, packages/default-layout/__tests__/dualPageCoverViewModeDifferentDimensionsZooming.e2e.ts, packages/default-layout/__tests__/dualPageViewModeDifferentDimensions.e2e.ts, packages/default-layout/__tests__/dualPageViewModeDifferentDimensionsAnnotation.e2e.ts, packages/default-layout/__tests__/dualPageViewModeDifferentDimensionsZooming.e2e.ts
=> feat: e2e tests for different viewmodes

packages/default-layout/__tests__/navigatePreviousNextPagesDualPageCoverViewMode.e2e.ts, packages/default-layout/__tests__/navigatePreviousNextPagesDualPageViewMode.e2e.ts
=> feat(e2e): Navigate to the previous and next pages in dual page viewmode

demo/nextjs/pages/default-layout-different-dimensions/index.tsx, jest-puppeteer.config.js, packages/default-layout/__e2e__/dualPageViewModeDifferentDimensionsAnnotation.e2e.ts, packages/default-layout/__e2e__/dualPageViewModeDifferentDimensionsZooming.e2e.ts
=> Viewmode e2e tests

CHANGELOG.md, packages/core/src/index.d.ts, packages/core/src/layouts/Inner.tsx, packages/core/src/types/RenderViewer.ts
=> feat: Add pagesContainerRef to RenderViewer

CHANGELOG.md, packages/core/src/layers/TextLayer.tsx, packages/core/src/layouts/Inner.tsx, packages/core/src/types/PdfJs.ts
=> feat: Support pdf-js 3.2.146

changelogs/v3.11.0.md, demo/nextjs/pages/core-initial-page-dual-page/index.tsx, packages/core/__e2e__/initialPageDualPageViewmode.e2e.ts, packages/core/src/layouts/Inner.tsx, packages/core/src/virtualizer/useVirtual.ts
=> fix: The dual page viewmode doesn't work well with the initial page

changelogs/v3.11.0.md, demo/nextjs/pages/core-render-protected-view/index.tsx, packages/core/__e2e__/renderProtectedView.e2e.ts, packages/core/__tests__/renderProtectedView.test.tsx, packages/core/src/Viewer.tsx, packages/core/src/index.d.ts, packages/core/src/index.ts, packages/core/src/loader/AskForPasswordState.ts, packages/core/src/loader/AskingPassword.tsx, packages/core/src/loader/DocumentLoader.tsx, packages/core/src/structs/PasswordStatus.ts, packages/core/src/types/PdfJs.ts, packages/core/src/types/RenderProtectedView.ts, packages/core/src/types/index.ts
=> feat: Customize the view of a protected document

changelogs/v3.11.0.md, demo/webpack/src/App.tsx, packages/page-navigation/__e2e__/jumpBackPreviousAnnotation.e2e.ts, packages/page-navigation/src/ShortcutHandler.tsx
=> feat: Change shortcut to jump back to previous clicked link annotation

changelogs/v3.11.0.md, packages/core/src/hooks/usePrevious.ts, packages/core/src/index.d.ts, packages/core/src/index.ts, packages/thumbnail/src/ThumbnailList.tsx, packages/thumbnail/src/ThumbnailListWithStore.tsx, packages/thumbnail/src/styles/theme.scss, packages/thumbnail/src/styles/thumbnailContainer.scss, packages/thumbnail/src/styles/thumbnailList.scss, packages/thumbnail/src/thumbnailPlugin.tsx, packages/thumbnail/src/types/StoreProps.ts
=> feat: Thumbnails are updated to look identically to pages

changelogs/v3.11.0.md, packages/core/src/virtualizer/useVirtual.ts, packages/default-layout/__e2e__/navigateLastPage.e2e.ts, packages/default-layout/__tests__/navigateLastPage.test.tsx
=> fix: Page navigation doesn't move to final page properly

changelogs/v3.11.0.md, packages/page-navigation/src/index.d.ts, packages/page-navigation/src/pageNavigationPlugin.tsx
=> feat: Expose functions to jump to the previous and next pages

changelogs/v3.11.0.md, demo/nextjs/pages/magazine/index.tsx, packages/thumbnail/src/ThumbnailList.tsx, packages/thumbnail/src/ThumbnailListWithStore.tsx, packages/thumbnail/src/index.d.ts, packages/thumbnail/src/index.ts, packages/thumbnail/src/scrollToBeVisible.ts, packages/thumbnail/src/structs/ThumbnailDirection.ts, packages/thumbnail/src/styles/thumbnailList.scss, packages/thumbnail/src/thumbnailPlugin.tsx
=> feat: Thumbnails component provides new direction property

changelogs/v3.12.0.md, packages/core/src/index.d.ts, packages/core/src/index.ts, packages/zoom/src/PinchZoom.tsx, packages/zoom/src/zoomPlugin.tsx
=> feat: Uses can zoom by pinching a trackpad

changelogs/v3.12.0.md, packages/bookmark/src/BookmarkItem.tsx, packages/bookmark/src/BookmarkList.tsx, packages/bookmark/src/BookmarkListRoot.tsx, packages/bookmark/src/BookmarkListWithStore.tsx, packages/bookmark/src/BookmarkLoader.tsx, packages/bookmark/src/types/StoreProps.ts, packages/core/src/annotations/AnnotationLayer.tsx, packages/core/src/annotations/AnnotationLayerBody.tsx, packages/core/src/annotations/Link.tsx, packages/core/src/hooks/useLIFOStack.ts, packages/core/src/hooks/useQueue.ts, packages/core/src/hooks/useStack.ts, packages/core/src/index.d.ts, packages/core/src/layers/PageLayer.tsx, packages/core/src/layouts/Inner.tsx, packages/core/src/layouts/useDestination.ts, packages/core/src/types/Destination.ts, packages/core/src/types/PluginFunctions.ts, packages/core/src/types/index.ts, packages/core/src/utils/managePages.ts, packages/highlight/src/highlightPlugin.tsx, packages/highlight/src/types/StoreProps.ts, packages/page-navigation/src/ShortcutHandler.tsx, packages/page-navigation/src/pageNavigationPlugin.tsx, packages/page-navigation/src/types/StoreProps.ts, packages/search/src/Highlights.tsx, packages/search/src/types/StoreProps.ts
=> feat: Navigate between destinations

packages/core/src/hooks/useQueue.ts, packages/core/src/layouts/useDestination.ts
=> fix: Users have to press shortcut twice

changelogs/v3.12.0.md, packages/core/src/Viewer.tsx, packages/core/src/index.d.ts, packages/core/src/layouts/Inner.tsx, packages/core/src/virtualizer/useVirtual.ts
=> feat: Add a new property to disable smooth scroll

changelogs/v3.12.0.md, packages/core/src/Viewer.tsx, packages/core/src/index.d.ts, packages/core/src/layouts/Inner.tsx, packages/core/src/types/SetRenderRange.ts, packages/core/src/types/index.ts, packages/core/src/virtualizer/useVirtual.ts
=> feat: Add an option to determine the render range

changelogs/v3.12.0.md, demo/nextjs/pages/highlight/index.tsx, packages/core/src/styles/pageLayer.scss
=> feat: Custom elements added to the page layer can be positioned outside of page

changelogs/v3.12.0.md, packages/core/src/hooks/useRunOnce.ts, packages/core/src/layouts/Inner.tsx, packages/default-layout/__e2e__/initialPage.e2e.ts, packages/default-layout/__e2e__/scrollToInitialPage.e2e.ts
=> fix: Viewer scrolls to initialPage page automatically when resizing container

changelogs/v3.12.0.md, packages/full-screen/src/EnterFullScreen.tsx, packages/full-screen/src/ExitFullScreen.tsx, packages/full-screen/src/FullScreenModeTracker.tsx, packages/full-screen/src/ShortcutHandler.tsx, packages/full-screen/src/fullScreenPlugin.tsx, packages/full-screen/src/structs/FullScreenMode.ts, packages/full-screen/src/types/StoreProps.ts, packages/full-screen/src/useEnterFullScreen.ts, packages/full-screen/src/useWindowResize.ts
=> fix: Keep the current page when entering the full scroll mode

changelogs/v3.12.0.md, packages/core/src/hooks/useScroll.ts, packages/core/src/utils/smoothScroll.ts, packages/core/src/virtualizer/useVirtual.ts
=> fix: Smooth scroll triggers many unnecessary calculations

demo/nextjs/pages/full-screen-switch-scroll-mode/index.tsx, packages/core/src/fullscreen/useFullScreen.ts, packages/core/src/hooks/useMeasureRect.ts, packages/core/src/hooks/useScroll.ts, packages/core/src/index.d.ts, packages/core/src/layouts/Inner.tsx, packages/core/src/structs/FullScreenMode.ts, packages/core/src/types/PluginFunctions.ts, packages/core/src/utils/smoothScroll.ts, packages/core/src/virtualizer/useVirtual.ts, packages/full-screen/src/FullScreenModeTracker.tsx, packages/full-screen/src/useEnterFullScreen.ts
=> fix: Scroll to target page after entering the full-screen mode completes

packages/core/src/layouts/Inner.tsx
=> feat: Don't process virtualized items if smooth scrolling isn't done yet

changelogs/v3.12.0.md, demo/nextjs/pages/thumbnail-cover-width/index.tsx, packages/core/src/layouts/Inner.tsx, packages/core/src/styles/documentLoader.scss, packages/core/src/styles/index.scss, packages/core/src/styles/inner.scss, packages/core/src/styles/viewer.scss, packages/thumbnail/src/Cover.tsx, packages/thumbnail/src/CoverInner.tsx, packages/thumbnail/src/index.d.ts, packages/thumbnail/src/styles/cover.scss, packages/thumbnail/src/types/CoverProps.ts
=> feat: Add new width property for Cover

packages/core/src/hooks/useScroll.ts, packages/core/src/layouts/Inner.tsx, packages/core/src/utils/smoothScroll.ts, packages/default-layout/__e2e__/scrollMode.e2e.ts
=> fix(e2e): Keep the current page after switching the scroll mode

packages/core/src/hooks/useScroll.ts, packages/default-layout/__e2e__/scrollModeRtl.e2e.ts
=> fix(e2e): Switch scroll mode in RTL

.prettierignore, demo/nextjs/next.config.js, demo/nextjs/package.json, demo/nextjs/pages/_app.tsx, packages/core/src/layouts/Inner.tsx
=> fix: Race condition where viewer doesn't scroll to target page

packages/core/src/layouts/Inner.tsx, packages/core/src/virtualizer/useVirtual.ts
=> fix: Keep special zoom level when resizing pages container

packages/core/src/layouts/Inner.tsx
=> fix: Reset queue when enableSmoothScroll is set to false

.gitignore, lerna.json, package.json, packages/attachment/package.json, packages/bookmark/package.json, packages/core/package.json, packages/default-layout/package.json, packages/drop/package.json, packages/full-screen/package.json, packages/full-screen/src/fullScreenPlugin.tsx, packages/get-file/package.json, packages/highlight/package.json, packages/legacy-worker/package.json, packages/locale-switcher/package.json, packages/open/package.json, packages/page-navigation/package.json, packages/print/package.json, packages/properties/package.json, packages/rotate/package.json, packages/scroll-mode/package.json, packages/search/package.json, packages/selection-mode/package.json, packages/theme/package.json, packages/thumbnail/package.json, packages/toolbar/package.json, packages/worker/package.json, packages/zoom/package.json, turbo.json
=> feat: Replace lerna with turbo

changelogs/v3.13.0.md, demo/nextjs/pages/api/doc/[...slug].ts, packages/core/src/Viewer.tsx, packages/core/src/layouts/Inner.tsx, packages/core/src/layouts/PageSizeCalculator.tsx
=> fix: Render the initial page without loading the document completely

packages/core/src/portal/Popover.tsx, packages/core/src/portal/Portal.tsx, packages/core/src/utils/determineBestPosition.ts
=> fix: Adjust the arrow position based on the best placement

demo/nextjs/pages/core-rotate-page-with-thumbnails/index.tsx, demo/nextjs/pages/core-rotate-page/index.tsx, demo/nextjs/pages/default-layout-rotate-page/index.tsx, demo/nextjs/pages/thumbnail-rotate-page/index.tsx, packages/core/src/index.d.ts, packages/core/src/portal/Tooltip.tsx, packages/core/src/portal/TooltipBody.tsx, packages/core/src/styles/tooltipBody.scss, packages/default-layout/src/Sidebar.tsx, packages/full-screen/src/EnterFullScreenButton.tsx, packages/full-screen/src/ExitFullScreenButtonWithTooltip.tsx, packages/get-file/src/DownloadButton.tsx, packages/open/src/OpenButton.tsx, packages/page-navigation/src/GoToFirstPageButton.tsx, packages/page-navigation/src/GoToLastPageButton.tsx, packages/page-navigation/src/GoToNextPageButton.tsx, packages/page-navigation/src/GoToPreviousPageButton.tsx, packages/print/src/PrintButton.tsx, packages/properties/src/ShowPropertiesButton.tsx, packages/rotate/src/RotateButton.tsx, packages/scroll-mode/src/SwitchScrollModeButton.tsx, packages/scroll-mode/src/SwitchViewModeButton.tsx, packages/search/src/SearchPopover.tsx, packages/search/src/ShowSearchPopoverButton.tsx, packages/selection-mode/src/SwitchSelectionModeButton.tsx, packages/theme/src/SwitchThemeButton.tsx, packages/toolbar/src/MoreActionsPopover.tsx, packages/zoom/src/ZoomInButton.tsx, packages/zoom/src/ZoomOutButton.tsx
=> feat: Use new Portal component for Tooltip

packages/core/src/hooks/useClickOutside.ts, packages/core/src/portal/ModalBody.tsx, packages/core/src/portal/PopoverBody.tsx
=> fix: Click outside a portal to close it

packages/core/src/portal/ModalBody.tsx, packages/core/src/portal/PopoverBody.tsx, packages/core/src/portal/Tooltip.tsx, packages/core/src/portal/useClickOutsideStack.ts
=> fix: Clicking outside topmost portal will close it

changelogs/v4.0.0.md, packages/core/src/annotations/AnnotationLoader.tsx, packages/core/src/hooks/useIsMounted.ts, packages/core/src/hooks/useSafeState.ts, packages/core/src/index.d.ts, packages/core/src/index.ts, packages/core/src/layers/PageLayer.tsx, packages/core/src/layouts/useOutlines.ts, packages/core/src/loader/DocumentLoader.tsx, packages/page-navigation/src/FetchLabels.tsx, packages/print/src/PageThumbnail.tsx, packages/print/src/PageThumbnailContainer.tsx, packages/thumbnail/src/CoverInner.tsx, packages/thumbnail/src/FetchLabels.tsx, packages/thumbnail/src/ThumbnailContainer.tsx
=> ref: Use new useSafeState hook

packages/core/src/portal/Portal.tsx, packages/core/src/utils/determineBestPosition.ts
=> fix: DOMRect is not defined in NextJS demo

packages/core/src/styles/arrow.scss, packages/core/src/styles/askingPassword.scss, packages/core/src/styles/menuDivider.scss, packages/core/src/styles/modalBody.scss, packages/core/src/styles/popoverBody.scss, packages/core/src/styles/separator.scss, packages/core/src/styles/textBox.scss, packages/core/src/styles/theme.scss, packages/default-layout/src/styles/defaultLayout.scss, packages/default-layout/src/styles/sidebar.scss, packages/default-layout/src/styles/theme.scss, packages/drop/src/styles/dropArea.scss, packages/drop/src/styles/theme.scss, packages/print/src/styles/printProgress.scss, packages/print/src/styles/theme.scss
=> feat: Add border color token

packages/attachment/src/styles/theme.scss, packages/bookmark/src/styles/theme.scss, packages/core/src/Viewer.tsx, packages/core/src/styles/theme.scss, packages/core/src/theme/withTheme.ts, packages/default-layout/src/styles/theme.scss, packages/drop/src/styles/theme.scss, packages/full-screen/src/styles/theme.scss, packages/print/src/styles/theme.scss, packages/thumbnail/src/styles/theme.scss, packages/toolbar/src/styles/theme.scss, packages/zoom/src/styles/theme.scss
=> fix: Portal components don't use the current theme context

packages/core/src/annotations/AnnotationLayerBody.tsx, packages/core/src/index.d.ts, packages/core/src/layers/PageLayer.tsx, packages/core/src/layers/TextLayer.tsx, packages/core/src/layouts/Inner.tsx, packages/core/src/types/Plugin.ts, packages/default-layout/src/defaultLayoutPlugin.tsx, packages/toolbar/src/toolbarPlugin.tsx
=> feat: A plugin can define its dependencies

changelogs/v4.0.0.md
=> fix: The loading spinner keeps showing forever

packages/core/src/styles/askingPassword.scss, packages/core/src/styles/button.scss, packages/core/src/styles/documentLoader.scss, packages/core/src/styles/minimalButton.scss, packages/core/src/styles/modalBody.scss, packages/core/src/styles/popoverBody.scss, packages/core/src/styles/primaryButton.scss, packages/core/src/styles/textBox.scss, packages/core/src/styles/tooltipBody.scss, packages/core/src/theme/darkTheme.ts, packages/core/src/theme/lightTheme.ts, packages/print/src/styles/printProgress.scss, packages/search/src/styles/highlight.scss
=> feat: Add border radius definitions

demo/nextjs/pages/core-render-protected-view/index.tsx, demo/nextjs/pages/print-pages/index.tsx, packages/core/__tests__/renderProtectedView.test.tsx, packages/core/src/styles/documentLoader.scss, packages/core/src/styles/theme.scss, packages/core/src/theme/darkTheme.ts, packages/core/src/theme/lightTheme.ts, packages/print/__tests__/setPagesFunction.test.tsx
=> feat: Add error color

packages/core/src/index.d.ts, packages/core/src/styles/arrow.scss, packages/core/src/styles/button.scss, packages/core/src/styles/link.scss, packages/core/src/styles/minimalButton.scss, packages/core/src/styles/pageLayer.scss, packages/core/src/styles/popoverBody.scss, packages/core/src/styles/tooltipBody.scss, packages/core/src/styles/viewer.scss, packages/core/src/theme/darkTheme.ts, packages/core/src/theme/lightTheme.ts, packages/core/src/theme/useTheme.ts, packages/core/src/types/Theme.ts, packages/default-layout/src/styles/defaultLayout.scss, packages/default-layout/src/styles/sidebar.scss, packages/print/src/styles/printProgress.scss, packages/search/src/styles/highlight.scss, packages/thumbnail/src/styles/thumbnailContainer.scss, packages/thumbnail/src/styles/thumbnailList.scss
=> feat: More tweaks of styles

demo/nextjs/pages/_app.tsx, packages/drop/package.json, packages/drop/src/DropArea.tsx, packages/drop/src/styles/dropArea.module.css, packages/drop/src/styles/index.scss, packages/toolbar/src/styles/index.scss
=>  feat: Use CSS module for drop plugin 

packages/open/package.json, packages/open/src/OpenButton.tsx, packages/open/src/styles/index.scss, packages/open/src/styles/openInput.module.css, packages/toolbar/src/styles/index.scss
=> feat: Use CSS module for open plugin

packages/selection-mode/package.json, packages/selection-mode/src/Tracker.tsx, packages/selection-mode/src/styles/index.scss, packages/selection-mode/src/styles/selectionMode.module.css, packages/toolbar/src/styles/index.scss
=> feat: Use CSS module for selection mode plugin

packages/drop/src/DropArea.tsx, packages/drop/src/styles/dropArea.module.css
=> fix: Incorrect CSS path

package.json, packages/attachment/package.json, packages/bookmark/package.json, packages/default-layout/package.json, packages/drop/package.json, packages/full-screen/package.json, packages/open/package.json, packages/page-navigation/package.json, packages/print/package.json, packages/properties/package.json, packages/search/package.json, packages/selection-mode/package.json, packages/thumbnail/package.json, packages/toolbar/package.json, packages/zoom/package.json, scripts/compile.ts
=>  fix: Extract generated CSS classes

packages/core/src/styles/textLayer.module.css, packages/selection-mode/src/styles/selectionMode.module.css
=> fix: Correct selectors

packages/core/src/fullscreen/useFullScreen.ts
=> fix: Page background isn't set properly in the full-screen mode

packages/core/src/components/Skeleton.tsx, packages/core/src/index.d.ts, packages/core/src/index.ts, packages/core/src/styles/skeleton.module.css
=> feat: Add new Skeleton component

packages/bookmark/src/BookmarkItemSkeleton.tsx, packages/bookmark/src/BookmarkListWithStore.tsx, packages/bookmark/src/BookmarkLoader.tsx, packages/bookmark/src/BookmarkSkeleton.tsx, packages/bookmark/src/styles/bookmarkListLoader.module.css, packages/bookmark/src/styles/bookmarkSkeleton.module.css, packages/core/src/index.ts, packages/core/src/utils/randomNumber.ts
=> feat: Show skeleton while bookmarks are being loaded
